### ISSUE TITLE
Running gradle-plugin with different AspectJ version

### ISSUE THREAD

**Issue by DaGeRe** [freefair/gradle-plugins#1005]
Unfortunately, AspectJ 1.9.21 does not support Java 8 and 11 anymore for compilation, but still for running. Therefore, I'd like to compile my aspects with AspectJ 1.9.20.1 (which would at least run with Java 11) and than have the 1.9.21 runtime dependency.

Is there a way to do so? 

I tried replacing the dependencies: https://github.com/kieker-monitoring/kieker/blob/KIEKER-1971-aspectj-update/monitoring/build.gradle but did not succeed here, it still uses AspectJ 1.9.21. The documentation states that changing the classpath is possible (https://docs.freefair.io/gradle-plugins/current/reference/#_io_freefair_aspectj_post_compile_weaving), however, I didn't find a way to do so.

**Comment by larsgrefer** [comment]
The post-compile-weaving tries to infer the AJC version from the runtime classpath of the corresponding source set.
If this does not work for you, you should be able to override this as follows:

```gradle
configurations {
    myCustomAjcConfiguration //ridiculously long name for clarity 
}

dependencies {
    myCustomAjcConfiguration "org.aspectj:aspectjtools:1.9.20.1"
}

compileJava {
    ajc {
        classpath.setFrom myCustomAjcConfiguration
    }
}

```

Alternatively you could specify that AJC should be invoked with a specific JVM version (while still compiling to an older Bytecode target):

```gradle
compileJava {
    targetCompatibility = "11"
    ajc {
        javaLauncher = javaToolchains.launcherFor { 
            languageVersion = JavaLanguageVersion.of(21)
        }
    }
}
```

**Comment by DaGeRe** [comment]
Thanks for the hints! Since we build on Java 11, we cannot change the Java version. But the first solution looks good.

Your code nearly works, the only thing I did differently was in `compileJava`, since just `aspectJCompileTime` could not be found:

```
compileJava {
	ajc {
		enabled = true
		// The classpath needs to be defined here
		classpath.setFrom project.configurations.aspectJCompileTime
	}
}
```

With this configuration, building the jar works in general (with `./gradlew clean mainJar aspectJJar -x check -x test`), but somehow executing the tests does not work (`./gradlew test`, in https://github.com/kieker-monitoring/kieker/actions/runs/7437785059/job/20236063677). 

I assume that this is due to our Gradle configuration and not due to the plugin behavior, so I'll have a look at this in the next days and close this issue after this is finished (or ask again if, against my expectations, this is somehow caused by the plugins behavior).

**Comment by larsgrefer** [comment]
I'm glad it worked. I've updated my comment to also include the `configurations.` prefix in the `compileJava.ajc` section.

Looking at your failing tests, it seems that you just need to adapt the solution for compileTestJava as well:

```gradle
compileTestJava {
    ajc {
        classpath.setFrom configurations.aspectJCompileTime
    }
}
```

**Comment by DaGeRe** [comment]
Thanks again! This fixed the issue, so configuring the classpath like this is a good option to keep the plugin usable with older Java versions.
