### ISSUE TITLE
Unabled to set the module path for the delombok task

### ISSUE THREAD

**Issue by clee-sofi** [freefair/gradle-plugins#105]
I'm getting lots of errors like "(package javax.persistence is declared in module java.persistence, which is not in the module graph)" when running the delombok task.

When looking at the code, it looks like the --module-path argument is not getting set as described here: https://projectlombok.org/features/delombok

**Comment by larsgrefer** [comment]
Thanks for bringing this up.

I can add a modulePath option to the delombok task, but I'm not sure which value I should pass in there

**Comment by clee-sofi** [comment]
At least for my compile task, I've been using:

compileJava {
    doFirst {
        options.compilerArgs = [
            '--module-path', classpath.asPath,
        ]
        classpath = files()  
    }
}

I'm not sure if you have access to the classpath from your task.

Also, as I quick workaround. Is it possible filter out module-info.java from being processed? I have a hunch that might work as well. Although maybe not always correct depending on the build process.

**Comment by clee-sofi** [comment]
Nice! works great. Thank you so much.
