### ISSUE TITLE
Make exploded dir configurable

### ISSUE THREAD

**Issue by cocorossello** [freefair/gradle-plugins#11]
It would be nice (and easy) to let a parameter explodedDir or explodedDestinationDir so it can be configured (convention is OK, but I would like to have my war on build/ROOT, so I can start tomcat with webapp pointing to that dir).

**Comment by larsgrefer** [comment]
Hi @cocorossello ,

try to add this to your `build.gradle`
```gradle
afterEvaluate {
    explodedWar {
        into "build/ROOT"
    }
}
```

**Comment by cocorossello** [comment]
Thanks, didn't know that!
