### ISSUE TITLE
Improve cacheability of AspectjCompile task

### ISSUE THREAD

**Issue by wilkinsona** [freefair/gradle-plugins#111]
The `AspectjCompile` task isn't as cacheable as it perhaps could be because its `source` property is using absolute path sensitivity. This means that caching doesn't work across two builds of identical code if the code is checked out into two different locations.

Gradle's `JavaCompile` task makes the `source` property use relative path sensitivity by [overriding the `getSource()` method]( https://github.com/gradle/gradle/blob/55a5e53d855db8fc7b0e494412fc624051a8e781/subprojects/language-java/src/main/java/org/gradle/api/tasks/compile/JavaCompile.java#L84-L88). If appropriate for AspectJ, and as far as I know it is, could the same be done for `AspectjCompile` please?

**Comment by larsgrefer** [comment]
@wilkinsona Thanks for pointing this out. I totally agree with you.

Your suggested fix is part of the just released `4.1.1`
It should be available from the Gradle Plugin Portal shortly.

**Comment by wilkinsona** [comment]
Wow. That was quick! Thanks very much.
