### ISSUE TITLE
Gradle Fails To Configure w/ package-registry-maven-publish

### ISSUE THREAD

**Issue by jamespedwards42** [freefair/gradle-plugins#112]
I'm not sure if this is an issue with the plugin, my configuration or Gradle, but figured I would check in here first.

Running `./gradlew check` with Gradle 5.6.2, Java 12.0.2 on a darwin amd64 Github Actions CI server I get the following exception.  However, running locally on MacOS I have no issues.  Removing the plugin resolves the issue. 

* Relevant build.gradle: https://github.com/comodal/json-iterator/blob/cb0118adfb687795e471bfcee98d55156a3a11af/systems.comodal.json_iterator/build.gradle#L9
* CI Failure: https://github.com/comodal/json-iterator/runs/235936473
* Backup of raw build logs: https://pastebin.com/1QbnmWRe

```
java.lang.IllegalStateException: No value has been specified for this provider.
  ...
  ...
  at io.freefair.gradle.plugins.github.GithubPackageRegistryMavenPublishPlugin.lambda$apply$1(GithubPackageRegistryMavenPublishPlugin.java:24)
  ...
```

**Comment by larsgrefer** [comment]
I assume the plugin fails to guess the slug (the repository identifier).
Try to manually set the slug to `comodal/json-iterator`

**Comment by jamespedwards42** [comment]
That fixed it! Thanks for the quick reply and excellent plugin.
