### ISSUE TITLE
New 8.8 release?

### ISSUE THREAD

**Issue by marcantoine-bibeau** [freefair/gradle-plugins#1141]
Is there an ETA for 8.8 release that include latest lombok version to support JDK 22?

Thanks!

**Comment by ablax** [comment]
+1

**Comment by larsgrefer** [comment]
I was pretty busy the last months, but new releases will come.

**Comment by BrandonDudek** [comment]
8.7 is also needed.

**Comment by marcantoine-bibeau** [comment]
And 8.9 ;)

**Comment by Sax388** [comment]
I'm pretty sure this issue can be closed as there's 8.10 now.
