### ISSUE TITLE
Working example that documents how to set compilerArgs

### ISSUE THREAD

**Issue by DaveJarvis** [freefair/gradle-plugins#117]
The [documentation](https://docs.freefair.io/gradle-plugins/4.1.1/reference/) shows:

``` java
compileJava {
    ajc {
        enabled = true 
        classpath = configurations.aspectj 
        options {
            aspectpath = configurations.aspect 
            compilerArgs = [] = 
        }
    }
}
```

The `ajc` reference cannot found by gradle.

Showing a complete example with a gradle file that references `ajc` and its compiler arguments (such as `-noImportError`) would be quite helpful.

Note: There is a typo `compilerArgs = [] = ` should be `compilerArgs = []`.  

See also: https://stackoverflow.com/q/58193520/59087

**Comment by larsgrefer** [comment]
Thanks for the detailed report.

`compileJava.ajc.options.compilerArgs += "-noImportError"` should work.
The notation used in the documentation should be fixed with the next release.

**Comment by DaveJarvis** [comment]
> compileJava.ajc.options.compilerArgs += "-noImportError" should work.

Thank you Lars. The `ajc` reference is not found by Gradle. I'll give it a try, but will changing the notation will help? (I think there's a deeper issue.) It would be nice to see a complete `build.gradle` file showing how `compileJava` works in Gradle 5 and Java 11.

**Comment by larsgrefer** [comment]
@DaveJarvis An example for the post-compile-weaving plugin can be found here:
https://github.com/freefair/gradle-plugins/blob/1d4ea3534227b7ced49a5821b8bdea023f65405a/examples/aspectj/weaving/build.gradle#L51-L57

The "normal" aspectj plugin has an example here:
https://github.com/freefair/gradle-plugins/blob/1d4ea3534227b7ced49a5821b8bdea023f65405a/examples/aspectj/aspect/build.gradle
