### ISSUE TITLE
Kotlin 2 compatibility

### ISSUE THREAD

**Issue by marcotama** [freefair/gradle-plugins#1258]
Hello!

Thanks for all the work you put in these plugins.
I was wondering, being new to them, are they compatible with Kotlin 2?
The compatibility matrix seems to indicate otherwise.
If yes, I recommend updating it so that people like myself are not ill advised.
If not, is there a timeline on adding support for it? I didn't find anything about this glancing at the open issues.

Thanks again

**Comment by larsgrefer** [comment]
For most of the plugins, the Kotlin version is irrelevant.

Some plugins may interface with the Kotlin Gradle plugin or are implemented in Kotlin.

Whenever possible, we use the same Kotlin version that Gradle uses, currently 2.0.22: https://docs.gradle.org/current/userguide/compatibility.html#kotlin

**Comment by Frisch12** [comment]
The compatibility matrix has been updated. It now reflects the latest changes. Kotlin 2.1 support will be complete in the next Gradle release.
