### ISSUE TITLE
Configure Export Directory

### ISSUE THREAD

**Issue by DaveJarvis** [freefair/gradle-plugins#128]
The plugin is being used in a standalone module (`app.aspects.weaver`) as follows:

``` groovy
apply plugin: 'java'
apply plugin: 'io.freefair.aspectj.post-compile-weaving'

dependencies {
    runtime "org.aspectj:aspectjrt:${aspectj.version}"

    compileOnly project(':app.project.main')

    inpath(project(':app.project.main')) {
        transitive = false
    }
}
```

The issue is that the woven classes must be "monkey patched" at a late stage in the build process, such as:

``` groovy
project( ":app.project.main" ) {
    testClasses.finalizedBy monkeyPatchBuild
}

compileJava.finalizedBy( project(":app.project.main").getTasksByName("monkeyPatchBuild", true) )

compileJava.ajc.options.compilerArgs += "-showWeaveInfo"
compileJava.ajc.options.compilerArgs += "-verbose"
```

Where the `app.project.main` build script resembles:

``` groovy
task monkeyPatchBuild(type: Copy) {
    doFirst {
        println("Monkey Patch Build Classes")
    }

    from project(':app.aspects.weaver').buildDir.toString() + "/classes/java/main"
    into "${project.buildDir}/classes/java/main"
}
```

It would be convenient if we could decouple the monkey patch dependency by exporting the woven classes directly to the `app.project.main` build folder, such as:

``` groovy
dependencies {
    runtime "org.aspectj:aspectjrt:${aspectj.version}"

    compileOnly project(':app.project.main')

    inpath(project(':app.project.main')) {
        transitive = false
    }

    // Overwrite the original class files in place with the woven class files.
    // This outpath call might have to copy the woven files from a temporary location.
    outpath(project(":app.project.main").buildDir)
}
```

Using the following did not work:

```
compileJava.ajc.options.compilerArgs += "-d " + project(":app.project.main").buildDir.toString()
```

This would eliminate the monkey patching.

**Comment by larsgrefer** [comment]
Why do you put the `io.freefair.aspectj.post-compile-weaving` in a separate gradle project?

As far as I can see, most of your problems would solve itself, if you apply it to `:app.project.main` directly

**Comment by DaveJarvis** [comment]
> Why do you put the io.freefair.aspectj.post-compile-weaving in a separate gradle project?

There are dozens of projects and we don't want to duplicate compile-time weaving in each one. Instead, we'd want to write something like:

``` groovy
    inpath(project(':app.project-1.main')) {transitive = false}
    inpath(project(':app.project-2.main')) {transitive = false}
```

The syntax doesn't much matter, it could also resemble:

``` groovy
    inpath([project(':app.project-1.main'), project[":app.project-2.main"]) {transitive = false}
```

Either way, fine-grained control over what projects get woven would be beneficial. The main projects themselves shouldn't need to know that the classes they generate are subsequently woven with aspects.

**Comment by larsgrefer** [comment]
I still feel that adding the `io.freefair.aspectj.post-compile-weaving` to the projects directly is what you need.

As alternative you could just use the `io.freefair.aspectj.base` plugin and define your own [`AspectjCompile`](https://docs.freefair.io/gradle-plugins/4.1.2/reference/#_aspectjcompile) task. When doing so, you have the complete control over the inputs and outputs.

**Comment by DaveJarvis** [comment]
There are 61 projects (and possibly more in the future): changing them is not feasible for several reasons.

> As alternative you could just use the io.freefair.aspectj.base plugin and define your own AspectjCompile task.

Thank you, I'll look into that a bit more. You mention `base` plugin, but the documentation shows:

``` groovy
task myAjcTask(type: io.freefair.gradle.plugins.aspectj.AspectjCompile) {
```

Instead of:

``` groovy
task myAjcTask(type: io.freefair.gradle.plugins.aspectj.base.AspectjCompile) {
```

It may be worthwhile clarifying in the documentation (section 5.1) as to what plugin is required for the AspectjCompile task.

**Comment by larsgrefer** [comment]
`io.freefair.aspectj.base` is a gradle plugin id and `io.freefair.gradle.plugins.aspectj` is a java package name, these are different things.

The `io.freefair.aspectj.base` plugin adds the `aspectj` extension and the `aspectj` configuration to the project. This allows you to use `aspectjClasspath = configurations.aspectj` inside your task definition.

**Comment by DaveJarvis** [comment]
Viele danke, @larsgrefer.
