### ISSUE TITLE
How to let AspectJ plugin work fine with Lombok plugin

### ISSUE THREAD

**Issue by ansonliao** [freefair/gradle-plugins#129]
Dear @larsgrefer , 
Months gone, thanks for solved my problem that the aspectj plugin in my Gradle project `hand by hand`.
Yes, here I have another issue about freefair plugins on how to let plugin `io.freefair.gradle:aspectj-plugin` works fine with plugin `io.freefair.lombok`, I did some search about this, it looks like Lombok will be disabled when works with AspectJ together in Gradle is the old problem, but after tries, I can't solve the problem.

Could you kindle provide some instruction that let plugin `io.freefair.gradle:aspectj-plugin` works fine with plugin `io.freefair.lombok`? or some existed project?

Great thanks for your help.

io.freefair.lombok

**Comment by larsgrefer** [comment]
The `io.freefair.aspectj` plugin doesn't work with lombok, because lombok doesn't support running in ajc.

The `io.freefair.aspectj.post-compile-weaving` however should work fine withe Lombok. (When this plugin is used, the code is first compiled with javac (and possibly Lombok) and the weaving then happens in a second step)

**Comment by ansonliaomelco** [comment]
@larsgrefer 
Thanks for your reply, let me try replace plugin `io.freefair.gradle:aspectj-plugin` with plugin `io.freefair.aspectj.post-compile-weaving`, any problem will update here.

**Comment by ansonliao** [comment]
Hi @larsgrefer , 
I updated my Aspectj Gradle sample project that added lombok plugin, and replaced aspectj plugin as you suggested, looks like these two plugins works well together, please kindly check if you are interested

https://github.com/ansonliao/Gradle-AspectJ-Sample/tree/3-investigate-how-to-let-aspectj-and-lombok-works-well-together

**Comment by mchades** [comment]
I've figured it out—it should work by simply adding:
```
id("io.freefair.aspectj.post-compile-weaving") version "8.14.2"
implementation("org.aspectj:aspectjrt:1.9.24")
```
For my project, since Jcstress is used, I need to add:
```
jcstressImplementation("org.aspectj:aspectjrt:1.9.24")
```
