### ISSUE TITLE
Tasks of type Javadoc are not patched by the plugin automatically

### ISSUE THREAD

**Issue by quotidian-ennui** [freefair/gradle-plugins#132]
If we have tasks of type Javadoc (but not called _javadoc_) then the source property is not patched automatically by the lombok plugin.
```
  task umlJavadoc(type: Javadoc) {
    group 'Documentation'
    description 'Build javadocs using plantuml + graphviz + umldoclet, if dot is available'

    onlyIf {
      hasGraphViz()
    } 
    // stuff skipped
 }
```
means that the javadoc task is run on the default source. Of course we can change the task to use the delombokTasks sourceSet
```
  task umlJavadoc(type: Javadoc) {
    group 'Documentation'
    description 'Build javadocs using plantuml + graphviz + umldoclet, if dot is available'

    onlyIf {
      hasGraphViz()
    } 
    source = sourceSets.main.extensions.delombokTask
    // stuff skipped
 }
```

However, it might just be easier to patch all tasks of type Javadoc instead of just the named javadoc task.

**Comment by larsgrefer** [comment]
Thanks for getting in touch.

Where is your `umlJavadoc` task getting its (default) source property from?

**Comment by quotidian-ennui** [comment]
It was set to  `source = sourceSets.main.allJava` which is why we configured it to be `source = sourceSets.main.extensions.delombokTask` when we switched the project to lombok; since we knew that it wouldn't work "as expected" w/o changes

However, it seemed little tricky to track down what the right setting was (this is either a documentation thing, or a "not fully in the gradle mindset thing"); hence the PR + issue (I browsed your sources in the end).

```
  javadoc {
    onlyIf {
      !hasGraphViz()
    }
    configure(options) {
      options.linksOffline(interlokJavadocs, offlineJavadocPackageDir.getCanonicalPath() + "/interlok-core-$interlokCoreVersion-javadoc.jar")
      options.linksOffline(interlokCommonJavadocs, offlineJavadocPackageDir.getCanonicalPath() + "/interlok-common-$interlokCoreVersion-javadoc.jar")
      taglets = ["com.adaptris.taglet.ConfigTaglet", "com.adaptris.taglet.LicenseTaglet"]
      options.addStringOption "tagletpath", configurations.javadoc.asPath
    }
  }
```
vs

```
  task umlJavadoc(type: Javadoc) {
    group 'Documentation'
    description 'Build javadocs using plantuml + graphviz + umldoclet, if dot is available'

    onlyIf {
      hasGraphViz()
    }
    source = sourceSets.main.extensions.delombokTask
    classpath = project.sourceSets.main.compileClasspath
    configure(options) {
      options.linksOffline(interlokJavadocs, offlineJavadocPackageDir.getCanonicalPath() + "/interlok-core-$interlokCoreVersion-javadoc.jar")
      options.linksOffline(interlokCommonJavadocs, offlineJavadocPackageDir.getCanonicalPath() + "/interlok-common-$interlokCoreVersion-javadoc.jar")
      taglets = ["com.adaptris.taglet.ConfigTaglet", "com.adaptris.taglet.LicenseTaglet"]
      options.addStringOption "tagletpath", configurations.javadoc.asPath
      options.docletpath = configurations.umlDoclet.files.asType(List)
      options.doclet = "nl.talsmasoftware.umldoclet.UMLDoclet"
    }
  }
  javadoc.dependsOn umlJavadoc
```

**Comment by larsgrefer** [comment]
The `javadoc` Javadoc task which is created by the `java` gradle plugin is the only Javadoc task which has a source by default. All other Javadoc tasks (like your `umlJavadoc`) must have their source explicitly set.

It feels wrong for me to let my gradle plugin override a value which was explicitly set.
That's why the plugin curently only touches the `javadoc` Javadoc task.

**Comment by quotidian-ennui** [comment]
Sure, it's your project (in which case close my associated PR).
It did seem "hard" to figure out the correct sources to put. So perhaps you can update the documentation so it's more obvious?
