### ISSUE TITLE
No value has been specified for this provider

### ISSUE THREAD

**Issue by breandan** [freefair/gradle-plugins#135]
Just thought you should know that [this plugin](https://plugins.gradle.org/plugin/io.freefair.github.package-registry-maven-publish) was the source of a [very frustrating bug](https://github.com/breandan/kotlingrad/commit/e877360c4d66abf42f43c6a62fa6e47ffc8debe6). FWIW I'm not sure if the issue was your fault directly since Gradle provides an [unhelpful stack trace](https://github.com/breandan/kotlingrad/runs/266853448#step:4:151), but after removing this plugin it was finally resolved. Anyway, GitHub now has [working Gradle instructions](https://help.github.com/en/articles/configuring-gradle-for-use-with-github-package-registry).

```
$ java --version
openjdk 11.0.4 2019-07-16
OpenJDK Runtime Environment (build 11.0.4+11-post-Ubuntu-1ubuntu218.04.3)
OpenJDK 64-Bit Server VM (build 11.0.4+11-post-Ubuntu-1ubuntu218.04.3, mixed mode, sharing)
```
```
$ gradle --version

------------------------------------------------------------
Gradle 5.6.3
------------------------------------------------------------

Build time:   2019-10-18 00:28:36 UTC
Revision:     bd168bbf5d152c479186a897f2cea494b7875d13

Kotlin:       1.3.41
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.14 compiled on March 12 2019
JVM:          11.0.4 (Ubuntu 11.0.4+11-post-Ubuntu-1ubuntu218.04.3)
OS:           Linux 4.15.0-65-generic amd64
```

**Comment by larsgrefer** [comment]
I assume that the plugin wasn't able to auto-detect the github repository slug.
I'll try to produce a more helpful stacktrace.
