### ISSUE TITLE
Lombok plugin does not work with Gradle 6

### ISSUE THREAD

**Issue by pucojazu** [freefair/gradle-plugins#144]
Hello,

I get the following Exception when I try to use the Lombok plugin with the now released Gradle 6.0:

`java.lang.ClassNotFoundException: org.gradle.api.plugins.quality.FindBugsExtension`

See attached log file for the complete StackTrace:
[build.log](https://github.com/freefair/gradle-plugins/files/3826272/build.log)
Here is also the build.gradle as txt-file because Github won't accept .gradle files: 
[build.txt](https://github.com/freefair/gradle-plugins/files/3826277/build.txt)

It looks like the plugin is using some FindBugs classes that were deprecated and removed with Gradle 6.

**Comment by ninja-** [comment]
solved in 4.1.4 :D

**Comment by pucojazu** [comment]
Works, thank you! :)
