### ISSUE TITLE
How to set the version of AspectJ being used

### ISSUE THREAD

**Issue by jej2003** [freefair/gradle-plugins#16]
I am trying to use version 1.8.9 of aspectj using the following

`
apply plugin: "io.freefair.aspectj.post-compile-weaving"
aspectj.version = '1.8.9'
`
but from what I see in the generated ajc.options still has the version 1.9.1 of the aspectj tools, runtime and weaver.  Is setting a custom version supported?  If so can you provide an example for how this should work?

**Comment by larsgrefer** [comment]
Can you run the `compileJava` of your project with the `--info` flag an post the output here?

**Comment by jej2003** [comment]
@larsgrefer, thanks for the quick turn on this!  I unfortunately can't verify until tomorrow morning (EST) but will do so as soon as I am back at my computer!

**Comment by larsgrefer** [comment]
Version 2.7.1 of the plug-in should fix your issue

**Comment by jej2003** [comment]
@larsgrefer, I may be looking at this incorrectly as I am not all that familiar with Gradle and plugins but doesn't look like it works properly still.  I am guessing that it's because in AspectJPostCompileWeavingPlugin on line 42:44 does not defer the actual weaving itself which means it picks up the 1.9.1 value that is set in the AspectJBasePlugin.  Am I interpreting this correctly?

**Comment by larsgrefer** [comment]
The plugin needs the aspectj version for 2 things:
* Adding the `aspectjrt` dependency to your project.
* Actually calling ajc for weaving.

You can see the version of `aspectjrt` in the generated ajc.options file. The version of ajc which is called can be found by running gradle with `--info`.

The version number is stored in the field `AspectJExtension#version` (you can access this field from your buildscript using `aspectj.version`)

Before 35824d3a8f150e2059a1778faaed60784714201f the `aspectjrt` dependency was created before your buildscript had a chance to change the version.

Please run `./gradlew clean compileJava --info` on your project and post the output of the `compileJava` task here.

**Comment by jej2003** [comment]
Sorry, this is part of a large multi-module build so I am going to try to pare down to the pieces that are relevant.  If I cut something out let me know and I'll dig it out

'
Compiling with JDK Java compiler API.
Starting process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/bin/java''. Working directory: /Users/jjohnson/project Command: /Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/bin/java -Dfile.encoding=UTF-8 -Duser.country=US -Duser.language=en -Duser.variant -cp /Users/jjohnson/.gradle/caches/modules-2/files-2.1/org.aspectj/aspectjtools/1.8.9/84ed8b38e2d7d7ba30ffce8fcdf8a63531d0c4ca/aspectjtools-1.8.9.jar org.aspectj.tools.ajc.Main -argfile /Users/jjohnson/project/build/tmp/compileJava/ajc.options
Successfully started process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/bin/java''
'
Which is the correct version but what is in ajc.options is not correct and I see this in the output as well.

'
[warning] bad version number found in /Users/jjohnson/.gradle/caches/modules-2/files-2.1/org.aspectj/aspectjrt/1.9.1/84b05e2d360c83ce9fd1780ab2b7f36565110b9c/aspectjrt-1.9.1.jar expected 1.8.9 found 1.9.1
'

The version that is in ajc.options is 1.9.1 for aspectjrt, weaver and tools.

**Comment by jej2003** [comment]
Please ignore, I think this is a dependency problem on my side, please ignore until I can run down.

**Comment by larsgrefer** [comment]
According to your log, `aspectjtools`/`ajc` 1.8.9 is used with `aspectjrt` 1.9.1.

When using this Gradle plugin, you don't have to declare any dependencies on aspectj yourself.
