### ISSUE TITLE
Domain freefair.io expired?

### ISSUE THREAD

**Issue by rud** [freefair/gradle-plugins#170]
Hi, 

Just a heads-up, currently getting:
```
host freefair.io                                                                                       
Host freefair.io not found: 3(NXDOMAIN)
```

**Comment by Frisch12** [comment]
Hi @rud,

Thank you for reaching us. We've found an issue in the domain system of our hoster and restored the domain from "The Void". 
It would be accessable again in 24 hours. 

Thank you very much.
