### ISSUE TITLE
Weaving Aspect into src/test/java coding

### ISSUE THREAD

**Issue by reebow** [freefair/gradle-plugins#177]
Hi @larsgrefer ,
I am using your plugin to do compile post compile weaving. I would like to write kind of integration test to see if the Jointpoint works. 
Therefor I would like to weave code around test classes as well.
Is this possible already? How could I achieve this?

Thank you very much,
Tim

**Comment by larsgrefer** [comment]
This line in your build.gradle should do:

```
compileTestJava.ajc.options.aspectpath.from sourceSets.main.output
```

**Comment by reebow** [comment]
Hi @larsgrefer,
thank you for your quick response. The weaving works now also in test!
But now I have the issue that the aspect method is getting called twice.

**Comment by larsgrefer** [comment]
> But now I have the issue that the aspect method is getting called twice.

@reebow Can you provide an [MCVE](https://stackoverflow.com/help/minimal-reproducible-example) for that problem?

**Comment by reebow** [comment]
@larsgrefer  here is my project: https://github.com/reebow/LogA
If you run the test you will see it goes twice into the method.

**Comment by larsgrefer** [comment]
Your pointcut matches both the call and the execution of `de.reebow.loga.LogInputAspectTest#methodUnderTest` therefore it's executed twice:

```java
class LogInputAspectTest {

    //...

    @LogInput
    public void methodUnderTest(String name, int age) {
        JoinPoint var3 = Factory.makeJP(ajc$tjp_0, this, this, name, Conversions.intObject(age));
        LogInputAspect.aspectOf().logInput(var3);
    }

    //...

    @Test
    @DisplayName("Method with Annotation @LogInput - invoke method - log method name, parameter types, name and value")
    void logInput() {
        byte var4 = 1;
        String var5 = "Daria";
        JoinPoint var3 = Factory.makeJP(ajc$tjp_1, this, this, var5, Conversions.intObject(var4));
        LogInputAspect.aspectOf().logInput(var3);
        this.methodUnderTest(var5, var4);
        List logEvents = this.appender.getLogEvents();
        Assertions.assertEquals(1, logEvents.size());
        LogEvent logEvent = (LogEvent)logEvents.get(1);
        Assertions.assertEquals(StandardLevel.DEBUG, logEvent.getLevel().getStandardLevel());
    }

    //...
}
```

The de-compiled code clearly shows that the advice is also invoked from the call site in `de.reebow.loga.LogInputAspectTest#logInput`

You could expand your pointcut expression to `@annotation(de.reebow.loga.annotations.LogInput) && execution(* *(..))` so it only matches the method execution but not the method call.

**Comment by reebow** [comment]
Ah thank you very much @larsgrefer!
I guess I still have to learn more about aop :) 

May I have one more question, how can I get the de-compiled code?

**Comment by larsgrefer** [comment]
I've just opened the `.class`-file with IntelliJ IDEA.

another option would be to run `javap -v Foo.class`
