### ISSUE TITLE
Add access to source sets for code generators

### ISSUE THREAD

**Issue by Favorlock** [freefair/gradle-plugins#194]
Would be good to have access to the different source sets of a project in code generators.

**Comment by Frisch12** [comment]
You have generateCode tasks for every source set that exists and your generator is called for every of these. 
I will check if I could add your requested feature easily. If not please give me some time to add it. Otherwise feel free to create a pull request 😄 

Tank you for your support 👍

**Comment by Favorlock** [comment]
Thanks. My main concern is that there didn't appear to be any file reference to the source sets directory. Would be good to have access to the directory along with any other relevant information about the source set.
