### ISSUE TITLE
Delombok removes explicit this

### ISSUE THREAD

**Issue by mkondratek** [freefair/gradle-plugins#217]
Having a class with methods that contain **explicit this**, like: 
`public void updateUI(@UnknownInitialization GitMacheteGraphTable this)`
**delombok** task generates code without the explicit this

**Comment by larsgrefer** [comment]
I think this issue should be reported to the lombok project itself: https://github.com/rzwitserloot/lombok/issues

**Comment by mkondratek** [comment]
Forwarding then, thanks!

**Comment by PawelLipski** [comment]
Resolved in Lombok (https://github.com/rzwitserloot/lombok/issues/2444)
