### ISSUE TITLE
Aggregate Jacoco Report - Unable to read execution data file test.exec

### ISSUE THREAD

**Issue by MarcelCoding** [freefair/gradle-plugins#231]
the task Task aggregateJacocoReport tries to read `test.exec` files from modules that don't have any because they don't have tests either.
```
Execution failed for task ':aggregateJacocoReport'.
> Unable to read execution data file G:\Coding\nova-project\nova-backend\nova-bootstrap\build\jacoco\test.exec
```
My solution: Filter the list of all `*.exec` files if they exist.

**Comment by larsgrefer** [comment]
This behaviour is caused by gradle itself: https://github.com/gradle/gradle/pull/9396
