### ISSUE TITLE
Application of all three aspectj plugins leads to "Failed to apply plugin [id 'org.gradle.java']"

### ISSUE THREAD

**Issue by joerghmeyer** [freefair/gradle-plugins#248]
Applying a kotlin build script based aspectj build with the following plugin configuration leands to 

Build file 'C:\dev\git\micrometer-test\build.gradle.kts' line: 9

An exception occurred applying plugin request [id: 'org.gradle.java']
> Failed to apply plugin [id 'org.gradle.java']
   > Cannot add a configuration with name 'aspect' as a configuration with that name already exists.

The stack trace is attached as file. Gradle version used is 6.5.1
[stacktrace.txt](https://github.com/freefair/gradle-plugins/files/5000582/stacktrace.txt)

plugins {

    id("io.freefair.aspectj.base") version "5.1.0"
    id("io.freefair.aspectj") version "5.1.0"
    id("io.freefair.aspectj.post-compile-weaving") version "5.1.0"

    // Apply the application plugin to add support for building a CLI application.
    java
    application
}

**Comment by larsgrefer** [comment]
Applying the `io.freefair.aspectj.base` is redundant as its automatically applied by the other to plugins.

`io.freefair.aspectj` and `io.freefair.aspectj.post-compile-weaving` are mutually exclusive.

What exactly are you trying to achieve?

**Comment by joerghmeyer** [comment]
I have java code and Aspect code in a single Gradle project. I tried that base can be left out. if I leave out the aspects plugin, the aspect folder in src/main/aspectj is not compiled. If I leave out the weaving plugin, the aspects are not woven.
Question: is it possible to compile aspects and apply them inside the same Gradle build project?

**Comment by larsgrefer** [comment]
> is it possible to compile aspects and apply them inside the same Gradle build project?
Yes.

When using the `io.freefair.aspectj` plugin, put both your aspects and the java code in `src/main/aspectj`.
Both will then be compiled and woven by ajc in one step.

When using the `io.freefair.aspectj.post-compile-weaving` plugin, put both in `src/main/java`.
In this case the code will be first compiled by javac and then woven by ajc.

If you have code-based aspects (*.aj files) you have to use the first option.
If you rely on javac plugins like lombok or want to weave aspects into code compiled by other compilers (groovyc, scalac, kotlinc) you have to use the second option.

**Comment by stancalau** [comment]
Hi! Any news on being able to run both plugins in the same build?
