### ISSUE TITLE
link to AspectJ examples

### ISSUE THREAD

**Issue by 3rojka** [freefair/gradle-plugins#25]
the link(https://github.com/freefair/gradle-plugin-examples/tree/master/aspectj) to examples on the aspectj plugin page(https://github.com/freefair/gradle-plugins/tree/master/aspectj-plugin) s is broken 

I could not find any examples anywhere, can you point me anywhere

**Comment by larsgrefer** [comment]
I've moved the example projects to this repo and updated the links accordingly.

The aspectj examples won't run on Gradle 5.0 because of gradle/gradle#7961, but you can use the latest 2.x version of the plugin on Gradle 4.10.x
