### ISSUE TITLE
post compile weaving of external jar files

### ISSUE THREAD

**Issue by AustinJavaCoder** [freefair/gradle-plugins#253]
I am interested in adding aspects to external jar files using the post compile method.
I am trying to use "io.freefair.aspectj.post-compile-weaving" but running into issues while referring to the external jar.
 ```
dependencies {
    aspect project(":my:aspectpoc")
}

dependencies {
    inpath project(":external:lib:extpoc")
}
```
is there a good example of how to do this using gradle?

**Comment by larsgrefer** [comment]
What issues are you running into?

**Comment by AustinJavaCoder** [comment]
Let's say I have this simple aspect (TestAspect ) that I want to weave into any given external jar file (source not available),
in this case test.jar (mypackage.* classes). I am looking for an example to start with, existing examples are not helping. I am not able to comprehend the right syntax to use here in gradle.

---------------------------------------------

package com.aspectj;

import org.aspectj.lang.annotation.Aspect;
import org.aspectj.lang.annotation.Before;
import org.aspectj.lang.JoinPoint;

@Aspect
public class TestAspect {

    @Before("execution (* mypackage.*(..))")
    public void advice(JoinPoint joinPoint) {
        System.out.println("TestAspect.advice() called on '%s'%n", joinPoint);
    }
}

**Comment by larsgrefer** [comment]
Your first example should work. Could you share the generated ajc.options file?

This example weaves a local aspect into an external jar: https://github.com/freefair/gradle-plugins/tree/master/examples/aspectj/httpcore-nio
