### ISSUE TITLE
Lombok plugin: "compileJava" task failed

### ISSUE THREAD

**Issue by ansonliao** [freefair/gradle-plugins#256]
- **IDE**: Intellij 2020.1.4, Mac
- **Plugin And Version**: io.freefair.lombok:5.1.1

I am running `io.freefair.lombok` plugin with version `5.1.1` and set up the Gradle plugin in `build.gradle` of my `TestNG` testing project as below:
```bash
plugins {
    id "io.freefair.lombok" version "5.1.1"
}
```

when I run my testing such as: `./gradlew clean test`
and getting the `compileJava` task failed with the error message as below:
```bash
> Task :compileJava FAILED
...
...[the_path_related_to_some_java_class]/LimoBookNowPage.java:154: error: cannot find symbol
        getPickupLoc().clear();
        ^
  symbol:   method getPickupLoc()
  location: class LimoBookNowPage
```

and `limo.selenide.Fixtures` about `scheduledPickupTime` code snippet is:
```java
@Getter
public class BasePage {
    ...
    private final SelenideElement pickupLoc = $(byId("limBook.input.location.pickup"));
}
```

The `lombok` plugin of Intellij is installed and enabled annotation processing for the project.
![image](https://user-images.githubusercontent.com/6060224/90948608-06856980-e473-11ea-9705-a77de6fb1bad.png)

Please help to provide the suggestion for how to solve the problem as this stuck me for couples days.
Thanks.

**Comment by larsgrefer** [comment]
Your settings in IntelliJ should be irrelevant for the gradle plugin.

Can you provide an example project which reproduces the problem?

**Comment by ansonliao** [comment]
@larsgrefer 
understood, after I checked, I used another library also include `lombok`, it is 
```bash
dependencies {
    compile('org.testng:testng:6.14.3',
            'io.github.sskorol:test-data-supplier:1.7.0'
    )
}
```

When I created a new project to show the details of the failure, finally I found with the same `build.gradle` in the new project, no `lombok` compile java issue, I no idea what happened.
