### ISSUE TITLE
build failure when applying io.freefair.aspectj.post-compile-weaving plugin 

### ISSUE THREAD

**Issue by uooka** [freefair/gradle-plugins#26]
Heyo,

So I'm trying to apply the io.freefair.aspectj.post-compile-weaving plugin (3.0.0-rc.3) but I'm getting the following error.

Any suggestions?

    > Task :compileJava FAILED

    FAILURE: Build failed with an exception.

    * What went wrong:
    Execution failed for task ':compileJava'.
    > No value has been specified for this provider.

**Comment by larsgrefer** [comment]
This is probably gradle/gradle#7961

I assume you are using Gradle 5.0? If so, update to Gradle 5.1 RC or downgrade to 4.10.3

**Comment by uooka** [comment]
Sweet as! Thanks Lars, 'tis working perfectly!

**Comment by larsgrefer** [comment]
If your problem is fixed, please close this ticket.

**Comment by uooka** [comment]
Ten four red leader!
