### ISSUE TITLE
post compile provider error

### ISSUE THREAD

**Issue by bootcode1** [freefair/gradle-plugins#27]
hi. 
io.freefair.aspectj.post-compile-weaving plugin (3.0.0-rc.10.1)
gradle 5.0

15:02:04.657 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * What went wrong:
15:02:04.657 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] A problem occurred evaluating root project 'aspectj'.
15:02:04.657 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > Failed to apply plugin [id 'io.freefair.aspectj.post-compile-weaving']
15:02:04.657 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]    > Could not create an instance of type io.freefair.gradle.plugins.AjcAction.
15:02:04.657 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]       > org.gradle.api.provider.Property.value(Ljava/lang/Object;)Lorg/gradle/api/provider/Property;

downgrade gradle version 4.10.3

**➜  aspectj gradle wrapper --gradle-version=4.10.3 --distribution-type=bin

BUILD SUCCESSFUL in 0s
1 actionable task: 1 executed
➜  aspectj ./gradlew compileJava  --no-daemon --stacktrace

Welcome to Gradle 4.10.3!

Here are the highlights of this release:
 - Incremental Java compilation by default
 - Periodic Gradle caches cleanup
 - Gradle Kotlin DSL 1.0-RC6
 - Nested included builds
 - SNAPSHOT plugin versions in the `plugins {}` block

For more details see https://docs.gradle.org/4.10.3/release-notes.html

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/bit/Workspaces/java/aspectj/build.gradle' line: 30

* What went wrong:
A problem occurred evaluating root project 'aspectj'.
> Failed to apply plugin [id 'io.freefair.aspectj.post-compile-weaving']
   > Could not create an instance of type io.freefair.gradle.plugins.AjcAction.
      > org.gradle.api.provider.Property.value(Ljava/lang/Object;)Lorg/gradle/api/provider/Property;**

**Comment by bootcode1** [comment]
Thank you for your prompt reply. 

Is it not working properly on gradle 5.0 and plugin 3.0.0?

**Comment by larsgrefer** [comment]
There's a bug in Gradle 5.0, but it should work with Gradle 5.1 which was released in the meantime
