### ISSUE TITLE
InteliJ IDEA does not recognize AspectJ sources

### ISSUE THREAD

**Issue by sirinath** [freefair/gradle-plugins#272]
The `src\main\aspectj` and `src\test\aspectj` directories are not recognised as `Source Root` and `Test Root` directories when importing Gradle projects.

![image](https://user-images.githubusercontent.com/637415/93693894-582d1c80-fb23-11ea-8c7c-46529206132b.png)

**Comment by larsgrefer** [comment]
Works for me (even with custom sourceSets):

<img width="169" alt="Bildschirmfoto 2020-09-20 um 16 51 45" src="https://user-images.githubusercontent.com/6069961/93714237-9ba67b80-fb61-11ea-85b1-8f62cee89468.png">

I've tested this using IntelliJ 2020.2.2 and Gradle 6.5.1.

Which versions are you using?
And can you share an example project which reproduces the issue?

**Comment by sirinath** [comment]
2020.2.2 and Gradle 6.6.1

**Comment by larsgrefer** [comment]
When using the `io.freefair.aspectj.post-compile-weaving` plugin, `src/${sourceSet}/aspectj` is not a source root.

The `aspectj` source root is added by the `io.freefair.aspectj` plugin.
(In the same way, the `groovy` source root is added by the `groovy` plugin)
