### ISSUE TITLE
Ability to Specify Source Sets/Directory for Each Weaving Functionality using the Respective Plugin

### ISSUE THREAD

**Issue by sirinath** [freefair/gradle-plugins#273]
This follows [this comment](https://github.com/freefair/gradle-plugins/issues/248#issuecomment-667418877). Is it possible to modify the functionality of the plugins so that:
- all plugin looks at `src\*\aspectj` directory for `aj` files by default unless specified otherwise
- `src\*\java` code without annotation processors used is compiled with compile-time weaving by default unless specified otherwise
- all other compiler outputs produced by Groovy, Scala, Kotlin, etc. need to be compiled with post-compile weaving
- ability to specify which source sets/directories need runtime weaving which can be handled by a new plugin
- ability to source sets/directories for each plugin. E.g. 
  - `src\<compile or bytecode or load sourceset>\aspectj\**\*.aj` -> compile-time weaving or post-compile weaving or runtime/load-time weaving, 
    - `src\<compile sourceset>\aspectj\**\*.aj` -> compile-time weaving, 
    - `src\<bytecode sourceset>\aspectj\**\*.aj` -> post-compile weaving, 
    - `src\<load sourceset>\aspectj\**\*.aj` -> runtime/load-time weaving, 
  - `src\<compile or bytecode or load sourceset>\java\**\*.java` or `src\<compile or bytecode or load sourceset>\java\**\*.aj`  -> compile-time weaving or post-compile weaving or runtime/load-time weaving, 
    - ...
  - `src\<bytecode or load sourceset>\scala\**\*.scala` -> post-compile weaving or runtime/load-time weaving; or `src\<previous sourceset>\scala\**\*.aj` -> compile-time weaving or post-compile weaving or runtime/load-time weaving, 
    - ...
  - `src\<bytecode or load sourceset>\groovy\**\*.groovy` -> post-compile weaving or runtime/load-time weaving; or or `src\<previous sourceset>\groovy\**\*.aj` -> compile-time weaving or post-compile weaving or runtime/load-time weaving, 
    - ...
  - `src\<bytecode or load sourceset>\kotlin\**\*.kt` -> post-compile weaving or runtime/load-time weaving; or or `src\<previous  sourceset>\kotlin\**\*.aj` -> compile-time weaving or post-compile weaving or runtime/load-time weaving, 
    - ...
  - `src\<bytecode or load sourceset>\xxx\**\*.xxx` -> post-compile weaving or runtime/load-time weaving; or or `src\<previous  sourceset>\xxx\**\*.aj` -> compile-time weaving or post-compile weaving or runtime/load-time weaving, 
    - ...

Also,
- compile-time weaving
- post-compile weaving
- runtime/load-time weaving (can be a new plugin)
should be complementary and can be used in the same project. The source sets/directories each plugin handles should be mutually exclusive.

Also, rename `io.freefair.aspectj` to `io.freefair.aspectj.compile-time-weaving` to be expilicit on what it does.

**Comment by Frisch12** [comment]
Is this still an issue?
