### ISSUE TITLE
Support LZMA tarTrees

### ISSUE THREAD

**Issue by bric3** [freefair/gradle-plugins#281]
Currently the plugin doesn't support LZMA tar trees. So it's qui complicated to _decompress_ `tar.xz` archives.

**Comment by bric3** [comment]
Related to this issue https://github.com/gradle/gradle/issues/15065

**Comment by Frisch12** [comment]
As far as I understand this issue, it is completely dependent on gradle/gradle#15065

So I would close that one since it has to be fixed in gradle itself. Then you will be able to use tar.xz files with our plugins as well.

**Comment by bric3** [comment]
I supposed this could be supported by freefair plugins as a complementary feature.
Yet it would be better if supported by gradle core indeed.

**Comment by bric3** [comment]
@larsgrefer 👍 ❤️
