### ISSUE TITLE
[lombok-plugin] Provide a way to change the generated sources location

### ISSUE THREAD

**Issue by x80486** [freefair/gradle-plugins#285]
I'm using the `io.freefair.lombok` version `5.3.0`. By default, the `generated` (and `generated_tests`) sources location are at the `main` / `test` level:

![image](https://user-images.githubusercontent.com/34633617/99128375-a0733300-25d8-11eb-9b5e-1e03f9c533ff.png)

Is it possible to configure the plugin in such a way to change the default location? If not, would it be possible to add that feature?

**Comment by larsgrefer** [comment]
The only locations for generated sources are:

- `build/generated/sources/*/java/main` (ouputs of the `compileJava` task, configured by the `java` plugin)
- `build/delombok/main` (outputs of the `delombok` task, configured by the `io.freefair.lombok` plugin)
