### ISSUE TITLE
[lombok-plugin] Add lombok-mapstruct-binding

### ISSUE THREAD

**Issue by Chessray** [freefair/gradle-plugins#286]
Note the Project Lombok [changelog](https://projectlombok.org/changelog):

> BREAKING CHANGE: mapstruct users should now add a dependency to lombok-mapstruct-binding. This solves compiling modules with lombok (and mapstruct).

Took me some time to figure out what I actually needed to do in order to get this working with plugin version 5.3.0:

Every project/module using Lombok _and_ MapStruct has to add this line in the `dependencies`:

`annotationProcessor "org.projectlombok:lombok-mapstruct-binding:0.1.0"`

Would be nice if the plugin could support this directly.

**Comment by larsgrefer** [comment]
How are configuring/adding mapstruct in your build.gradle?

**Comment by Chessray** [comment]
> How are configuring/adding mapstruct in your build.gradle?

By adding these two dependencies:

        implementation "org.mapstruct:mapstruct:${mapstructVersion}"
        annotationProcessor "org.mapstruct:mapstruct-processor:${mapstructVersion}"
