### ISSUE TITLE
Java 10 support either on Gradle 4.10 or 5+

### ISSUE THREAD

**Issue by Hemantkumar-Chigadani** [freefair/gradle-plugins#29]
The following error keeping happening in Gradle 4.10 & 2.9.5(plugin version) or Gradle 5.2.1 & 3.1.0(plugin version).

May be I am missing a configuration? Where as AspectJ 1.9.2 claims to be supporting Java 10/11

> [error] invalid source option, source is either '1.3' or '1.4': 1.10
>         
> AspectJ Compiler 1.9.2
> 
>         Usage: <options> <source file | @argfile>..
> 
> AspectJ-specific options:

**Comment by larsgrefer** [comment]
Could you try Java 11?

IIRC this happens because Gradle reports Java 10 as `1.10` while ajc expects `10`

**Comment by Hemantkumar-Chigadani** [comment]
Thank you, Works on Java 11 with Gradle 5.2.1 & 3.1.0(plugin version).

**Comment by Hemantkumar-Chigadani** [comment]
Not sure this thread right to ask another question:

External built aop jar to be used in current gradle project using this plugin, is this possible to configure to scan even classpath or a specific path for aop external jar?

**Comment by larsgrefer** [comment]
External advices can be included using the `aspect` configuration:

https://github.com/freefair/gradle-plugins/blob/a8730fd83ebdf2976d6febc15f71c2604b142acc/examples/aspectj/weaving/build.gradle#L14-L15

Everything in the `aspect` configuration is passed as `-aspectpath` to ajc

**Comment by Hemantkumar-Chigadani** [comment]
Great having discussion here 👍
