### ISSUE TITLE
aspectJ: allow setting params in AspectjCompile options

### ISSUE THREAD

**Issue by IlyaNerd** [freefair/gradle-plugins#306]
I was trying to create my own AspectjCompile task, but all the fields in options are final.
I cant set anything, gradle just throws ex - Cannot set the value of read-only property 'inpath' for AspectJCompileOptions...

**Comment by larsgrefer** [comment]
The fields themselves are final, but the objects which are stored in the fields are mutable.

The fields of type `Property<*>` all have a `set()`-method. The FileCollections (like inpath) have a `from()` method.

More on this can be found here: https://docs.gradle.org/current/userguide/lazy_configuration.html
