### ISSUE TITLE
 Could not resolve io.freefair.gradle:lombok-plugin:5.3.0

### ISSUE THREAD

**Issue by indvamshi** [freefair/gradle-plugins#309]
Hi
We are facing issue on Jenkins pipeline with below error

Required by:
 project : > io.freefair.lombok:io.freefair.lombok.gradle.plugin:5.3.0
 Could not resolve io.freefair.gradle:lombok-plugin:5.3.0.
Could not parse module metadata lombok-plugin-5.3.0.module

Use JsonReader.setLenient(true) to accept malformed JSON at line 2 column 1 path $

Gradle Version : Gradle 6.8.3

Any idea what is the root cause?

Thanks
Vam

**Comment by larsgrefer** [comment]
Have you tried to clear your local gradle cache? (`~/.gradle/caches/modules-2/files-2.1`)
