### ISSUE TITLE
lombok plugin seems not working on vscode

### ISSUE THREAD

**Issue by jeusdi** [freefair/gradle-plugins#32]
I'm getting this error on vscode:

`GradleException: Could not generate a proxy class for class io.freefair.gradle.plugins.lombok.GenerateLombokConfig`

I've detailed a more at [here](https://github.com/GabrielBB/vscode-lombok/issues/21).

I thought you could help out...

**Comment by GabrielBB** [comment]
This issue can be closed. Please see: https://github.com/GabrielBB/vscode-lombok/issues/21#issuecomment-489354906
