### ISSUE TITLE
Code Generator - Could not find any convention object of type JavaPluginConvention

### ISSUE THREAD

**Issue by jamesmirvine** [freefair/gradle-plugins#326]
I'm trying to add the `code-generator` plugin to my project, but I'm getting the following error when running `gradle init` or `gradle build`:

> An exception occurred applying plugin request [id: 'io.freefair.code-generator', version: '5.3.3.3']
> 
> Caused by: java.lang.IllegalStateException: Could not find any convention object of type JavaPluginConvention.
> 	at org.gradle.internal.extensibility.DefaultConvention.getPlugin(DefaultConvention.java:78)
> 	at io.freefair.gradle.plugin.codegenerator.CodeGeneratorPlugin.apply(CodeGeneratorPlugin.java:19)
> 	at io.freefair.gradle.plugin.codegenerator.CodeGeneratorPlugin.apply(CodeGeneratorPlugin.java:12)

It's a simple one module project with one build.gradle (Gradle 6.5). Here's the top snippet:
```groovy
buildscript {
    ext {
        codeGeneratorVersion = "5.3.3.3"
    }
    dependencies {
        classpath 'com.google.googlejavaformat:google-java-format:1.7'
    }
}

plugins {
    id 'java'
    id 'eclipse'
    id 'idea'
    id 'jacoco'
    id "com.diffplug.gradle.spotless" version "3.26.1"
    id 'maven-publish'
    id 'nebula.release' version '13.0.0'
    id 'com.jfrog.artifactory' version '4.13.0'
    id 'com.github.ksoichiro.console.reporter' version '0.6.2'
    id 'io.freefair.lombok' version '5.3.0'
    id 'io.freefair.code-generator' version "$codeGeneratorVersion"
}
```

In the `code-generator` example it only shows that you need the `java` plugin, which I do. However if I turn on debug output from gradle then I don't see the `java` plugin applied before `io.freefair.code-generator` gets applied.

Digging a bit deeper, I ran gradle with a debugger and found that it considers some plugins to be "legacy" and applies them first. It throws the exception after [Line 122 of DefaultPluginRequestApplicator.java](https://github.com/gradle/gradle/blob/v6.5.0/subprojects/plugin-use/src/main/java/org/gradle/plugin/use/internal/DefaultPluginRequestApplicator.java#L122) runs. Here are the relevant variable values:

`legacyActualPluginIds`:

- {DefaultPluginRequestApplicator$Result@7100}  -> {DefaultPluginId@7101} "com.diffplug.gradle.spotless"
- {DefaultPluginRequestApplicator$Result@7102}  -> {DefaultPluginId@7103} "nebula.release"
- {DefaultPluginRequestApplicator$Result@7104}  -> {DefaultPluginId@7105} "com.jfrog.artifactory"
- {DefaultPluginRequestApplicator$Result@7106}  -> {DefaultPluginId@7107} "com.github.ksoichiro.console.reporter"
- {DefaultPluginRequestApplicator$Result@7108}  -> {DefaultPluginId@7109} "io.freefair.lombok"
- {DefaultPluginRequestApplicator$Result@7110}  -> {DefaultPluginId@7111} "io.freefair.code-generator"

`pluginImpls`:
- {DefaultPluginRequestApplicator$Result@7126}  -> {DefaultPluginRegistry$RegistryAwarePluginImplementation@7127} 
  - key = {DefaultPluginRequestApplicator$Result@7126} 
    - request = {DefaultPluginRequest@7137} "[id: 'java']"
- {DefaultPluginRequestApplicator$Result@7128}  -> {DefaultPluginRegistry$RegistryAwarePluginImplementation@7129} 
  - key = {DefaultPluginRequestApplicator$Result@7128} 
    - request = {DefaultPluginRequest@7150} "[id: 'eclipse']"
- {DefaultPluginRequestApplicator$Result@7130}  -> {DefaultPluginRegistry$RegistryAwarePluginImplementation@7131} 
  - key = {DefaultPluginRequestApplicator$Result@7130}
    - request = {DefaultPluginRequest@7154} "[id: 'idea']"
- {DefaultPluginRequestApplicator$Result@7132}  -> {DefaultPluginRegistry$RegistryAwarePluginImplementation@7133} 
  - key = {DefaultPluginRequestApplicator$Result@7132}
    - request = {DefaultPluginRequest@7158} "[id: 'jacoco']"
- {DefaultPluginRequestApplicator$Result@7134}  -> {DefaultPluginRegistry$RegistryAwarePluginImplementation@7135} 
  - key = {DefaultPluginRequestApplicator$Result@7134} 
    - request = {DefaultPluginRequest@7162} "[id: 'maven-publish']"

I've seen examples from other plugins that run `project.getPluginManager().apply(JavaPlugin.class);` before getting the convention to ensure it's available. I can submit an MR for this, but I wanted to check first to see if there's a better solution.

**Comment by larsgrefer** [comment]
Thanks for the detailed analysis. I'll have a look at it.
