### ISSUE TITLE
Lombok Plugin: Compiler warnings "no @param" for builder methods"

### ISSUE THREAD

**Issue by pluttrell** [freefair/gradle-plugins#327]
When switching from using direct dependencies to the Lombok plugin, compiler warnings show up for builder `set` using name override methods.

For example: 
```java
@Value
@Builder(builderMethodName="newBuilder", setterPrefix="with")
public class SomeType{
  String id;
}
```

Generates this compiler warning:
```
warning no @param for id
    public SomeType.SomeTypeBuilder withId(final String id) {
```

Experienced with: Gradle `7.0`, plugin version `6.0.0-m2`, Lombok v`1.18.20` and Java 11.

It doesn't happen if remove the plugin from my project and instead directly add: 
```groovy
	compileOnly 'org.projectlombok:lombok:1.18.20'
	annotationProcessor 'org.projectlombok:lombok:1.18.20'
	
	testCompileOnly 'org.projectlombok:lombok:1.18.20'
	testAnnotationProcessor 'org.projectlombok:lombok:1.18.20'
```

**Comment by larsgrefer** [comment]
Are you sure these are compiler warnings? It should "just" be javadoc warnings.

Without the plugin, the javadoc task runs on the "real" source-code so it does not see the builder methods which will be generated by lombok at all.

With the plugin, the javadoc task uses the delombok-ed source code as input, so the methods generated by lombok will be listed in the javadoc.

**Comment by larsgrefer** [comment]
See also https://stackoverflow.com/a/68505563/3574494

**Comment by frankjkelly** [comment]
I too am impacted by the same issue - we have a team-wide requirement of no javadoc warnings sadly

**Comment by larsgrefer** [comment]
I don't think that this(my) Gradle plugin has anything to do with this problem.
Maybe there is a regression in Lombok itself.
