### ISSUE TITLE
[Feature Request] Lombok Plugin: Update `withSourcesJar()` to use the delomboked source

### ISSUE THREAD

**Issue by pluttrell** [freefair/gradle-plugins#328]
Gradle's `JavaPluginExtension` includes a `withSourcesJar()` that automatically packages source code ([reference docs](https://docs.gradle.org/current/dsl/org.gradle.api.plugins.JavaPluginExtension.html#org.gradle.api.plugins.JavaPluginExtension:withSourcesJar())).

This is a feature request for the Lombok plugin to change the source to the delomboked source.

**Comment by larsgrefer** [comment]
The sourcesJar task currently does not use the delombok-ed sources on purpose.

With the current setup the line-numbers of the source code inside the `-sources` jar and the LineNumberTable inside the `.class`-files inside the normal jar match each other.

**Comment by ErwanLeroux** [comment]
How can we  use the delombok-ed sources with the sourcesJar ?
An easy option inside the plugin would be nice

**Comment by larsgrefer** [comment]
This should do the trick:

```gradle
sourcesJar {
    exclude {
        sourceSets.main.allSource.contains it.file
    }
    from delombok
}
```
