### ISSUE TITLE
Duplicate jars with different version. 

### ISSUE THREAD

**Issue by kittugit** [freefair/gradle-plugins#33]
Resulting war file contains duplicate entries of same jars with different version.  like 
spring-orm-4.1.9.RELEASE.jar
spring-orm-4.3.18.RELEASE.jar

Expected: only spring-orm-4.3.18.RELEASE.jar  (higher vesion)

Version: 'io.freefair.war-overlay' version '3.1.4'

Can someone help me to fix this? or Any direction to fix this error is welcome.

**Comment by larsgrefer** [comment]
The `WEB-INF/lib` folder is copied from the overlay as-is. If you don't want this you can exclude it and re-declare all the dependencies yourself:

```gradle
war {
    overlays {
        foo {
            exclude "WEB-INF/lib/*        
        }
    }
}
```

**Comment by kittugit** [comment]
Thanks for your response.  I have to include WEB-INF/lib from overlay.   There are extra dependencies added in the project.  So few jars have version conflict.  for example,  overlay lib has "spring-orm-4.3.18.RELEASE.jar" and my extra dependency(transitive) has "spring-orm-4.1.9.RELEASE.jar".  In this case, i want to add only higher version of the jar (as default in gradle)  in the resulting war file.

**Comment by larsgrefer** [comment]
Unfortunately, the jars from the `WEB-INF/lib` directory in the overlay can't participate in Gradle's dependency resolution. If you have problems with those jars, the easiest solution is to exclude them from the overlay and declare them as explicit dependencies:

```gradle
war {
    overlays {
        foo {
            exclude "WEB-INF/lib/spring-orm-*.jar"
        }
    }
}

dependencies {
    compile "org.springframework:spring-orm:4.3.18.RELEASE"
}
```
