### ISSUE TITLE
Delombok quiet flag not respected

### ISSUE THREAD

**Issue by adriendengreville** [freefair/gradle-plugins#337]
Using :
- io.freefair.lombok plugin version `5.3.3.3`
- Gradle version `7.0`
- Kotlin version `1.5.0`
- Java version `16`

When adding this task configuration 
```kotlin
tasks.withType<io.freefair.gradle.plugins.lombok.tasks.Delombok> {
    this.quiet.set(true)
}
```
the quiet flag is actually passed to the `delombok.options` file :
```
--format=pretty
--quiet
--encoding=UTF-8
--target=...
```

But when running `gradle delombok` on my project, I still get the warnings and errors on the standard output.
Here is an example of such logs : 
```
/XXX.java:11: warning: Generating equals/hashCode implementation but without a call to superclass, even though this class does not extend java.lang.Object. If this is intentional, add '@EqualsAndHashCode(callSuper=false)' to your type.
@Data
^
/XXX.java:6: error: package YYY does not exist
import YYY;
```

My code (a mix of Kotlin and Lomboked Java in a single module) actually compiles once the delombok step is executed. I really just need the `--quiet` flag to be respected.

**Comment by larsgrefer** [comment]
Interesting. Thanks for the detailed information.

Unfortunately, this seems to be not caused by the Gradle plugin but an issue in (de)lombok itself.

As I was able to reproduce this on the command line by invoking delombok directly, I'd suggest to report this here: https://github.com/projectlombok/lombok/issues

**Comment by materemias** [comment]
on the side note: @adriendengreville how could you get kotlin and lomboked java work?
I got to
```
compileKotlin {
    dependsOn(delombok)
    sourceSets.main {
        java.srcDirs("${project.buildDir}/generated/sources/delombok/java/main")
    }
}
```
but idea freaks out because of duplicate classes. could you point me how to do the integration?

**Comment by adriendengreville** [comment]
Thanks for your analysis @larsgrefer, but when I see Lombok's issue stack, I feel like it's not even worth opening an issue about that 😅

Sure thing @materemias, the following did the trick:
```kotlin
kotlin.sourceSets["main"].apply {
    kotlin.setSrcDirs(emptyList<String>())
}

tasks.withType<KotlinCompile> {
    dependsOn("delombok")
    setSource(file("build/generated/sources/delombok/java/main"))
}
```
The `kotlin.setSrcDirs` line tricks Intellij into thinking that it doesn't need to add the sources defined in `setSource` to the active files. Note that I'm using Gradle's Kotlin DSL.

**Comment by materemias** [comment]
Thanks for the hint @adriendengreville, the trick works fine!

**Comment by materemias** [comment]
@adriendengreville I have experimented with turning some of my java classes to kotlin and experienced this error
```
 Entry META-INF/mymodule.kotlin_module is a duplicate but no duplicate handling strategy has been set. Please refer to https://docs.gradle.org/7.0.2/dsl/org.gradle.api.tasks.Copy.html#org.gradle.api.tasks.Copy:duplicatesStrategy for details.
```
did you experience something similar? do you have a solution for this?

**Comment by overfullstack** [comment]
@adriendengreville with that setup, has anything broke for you with the new plugin v6.2.0? I have upgraded and delombok behaves strangely. I haven't been able to zero out the problem yet, but I see no java classes in this folder after delombok. `build/generated/sources/delombok/java/main`
Sample project: https://github.com/overfullstack/vader-root/blob/master/specs/build.gradle.kts
