### ISSUE TITLE
Support lombok.disableConfig system property

### ISSUE THREAD

**Issue by aalistairr** [freefair/gradle-plugins#343]
When the `lombok.disableConfig` system property is set, Lombok uses a configuration resolver that returns `null` for any configuration key (https://github.com/projectlombok/lombok/blob/master/src/core/lombok/core/LombokConfiguration.java#L48).

The lombok plugin could support this property too, with perfomance gains as result for large composite builds of multi-projects with multiple sourcesets.

```
if (System.getProperty("lombok.disableConfig") != null) {
    return;
}
```
at https://github.com/freefair/gradle-plugins/blob/master/lombok-plugin/src/main/java/io/freefair/gradle/plugins/lombok/LombokPlugin.java#L129 seems to work alright for us.

**Comment by matthijs-oosterhoff** [comment]
I could use this change too :+1:
