### ISSUE TITLE
Update JQuery version used in JavaDocs

### ISSUE THREAD

**Issue by willarmiros** [freefair/gradle-plugins#349]
Hello,

I'm using the `io.freefair.aggregate-javadoc-jar` plugin and Gradle 6.9 to generate a JavaDoc JAR for my project. From the source in this repo, it appears to use the built-in Gradle JavaDoc task under the hood to generate javadocs for individual gradle subprojects. I run `./gradlew aggregateJavadocJar` to get the docs JAR in my `build/libs` directory. The problem is, they're generated with `jquery-3.4.1.js` included, which has a [known XSS vulnerability](https://snyk.io/vuln/npm:jquery@3.4.1). 

More confusing, is that Gradle upgraded their JQuery version in https://github.com/gradle/gradle/pull/14121, but I still get the old 3.4.1 despite using a Gradle version that includes this upgrade. My ask is if you could point me in the direction of how to update JQuery for these auto-generated docs, or where I can make a PR against this plugin to do so for all users of it.

**Comment by larsgrefer** [comment]
The jQuery version used in the javadocs depends on the version of your javadoc tool / JDK

For JDK 15+ jQuery was updated to 3.5.1 here: https://github.com/openjdk/jdk/commit/0b02c5b5e038db4b86d15a2a99a3a3fd051f406d
