### ISSUE TITLE
Apply aspects from maven 

### ISSUE THREAD

**Issue by rmeloca** [freefair/gradle-plugins#35]
Is it possible to apply aspects coming from maven local dependencies?

**Comment by larsgrefer** [comment]
Sure:

```gradle
apply plugin: "io.freefair.aspectj.post-compile-weaving"

repositories {
    mavenCentral()
    mavenLocal()
}

dependencies {
    aspect 'com.example.foo:bar-aspect:1.2.3'
}
```

**Comment by rmeloca** [comment]
Thank you.

I've initially got `Plugin with id 'io.freefair.aspectj.post-compile-weaving' not found.`, but when using `with plugins {id "io.freefair.aspectj.post-compile-weaving" version "3.1.4"}` it worked fine.
