### ISSUE TITLE
aspectj.post-compile-weaving & lombok compileJava error 'path may not be null or empty string. path="null"'

### ISSUE THREAD

**Issue by tbert12** [freefair/gradle-plugins#354]
Hi, I'm trying to add lombok + aspectj post-compile-waving plugins on the project.
I have the following lines in `build.gradle`
```
...
plugins {
    id "java"
    id "idea"
    id "io.freefair.lombok" version "5.3.3.3"
    id "io.freefair.aspectj.post-compile-weaving" version "5.3.3.3"
}
aspectj.version = '1.9.6'
...
```

When I try to compile the project, throws this error (exception):
```
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':compileJava'.
Caused by: java.lang.IllegalArgumentException: path may not be null or empty string. path='null'
	at io.freefair.gradle.plugins.aspectj.internal.AspectJCompiler.createCompilerHandle(AspectJCompiler.java:102)
```

what is wrong on the `build.gradle` file?

**Comment by Frisch12** [comment]
Hey @tbert12 

Thank you for your submission and sorry for your long waiting time. 

Seems to work with the current version 6.4.1. Can you try it again? 

Thanks,
Dennis
