### ISSUE TITLE
Cannot apply 'io.freefair.aspectj' plugin.

### ISSUE THREAD

**Issue by ksiczek** [freefair/gradle-plugins#358]
Hi there,

I am trying to migrate a rather large and messy codebase to Gradle 5 and I have some issues replacing our current nl.eveoh:gradle-aspectj plugin with the io.freefair.aspectj one. Our project uses compile-time weaving using an already compiled aspects library. Basically, I removed the old plugin I have added only 

```
plugins {
  id "io.freefair.aspectj" version "5.3.3.3"
}
```

but I cannot make it work and the issue depends on the Gradle version

For
```
------------------------------------------------------------
Gradle 5.0
------------------------------------------------------------

Build time:   2018-11-26 11:48:43 UTC
Revision:     7fc6e5abf2fc5fe0824aec8a0f5462664dbcd987

Kotlin DSL:   1.0.4
Kotlin:       1.3.10
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.13 compiled on July 10 2018
JVM:          1.8.0_241 (Oracle Corporation 25.241-b07)
OS:           Linux 5.12.12-300.fc34.x86_64 amd64
``` 
it is 
```
* What went wrong:
An exception occurred applying plugin request [id: 'io.freefair.aspectj', version: '5.3.3.3']
> Failed to apply plugin [class 'io.freefair.gradle.plugins.aspectj.AspectJBasePlugin']
   > Could not create an instance of type io.freefair.gradle.plugins.aspectj.AspectJExtension_Decorated.
      > Could not find any public constructor for class io.freefair.gradle.plugins.aspectj.AspectJExtension_Decorated which accepts parameters [].
```

and for
```
------------------------------------------------------------
Gradle 5.4
------------------------------------------------------------

Build time:   2019-04-16 02:44:16 UTC
Revision:     a4f3f91a30d4e36d82cc7592c4a0726df52aba0d

Kotlin:       1.3.21
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.13 compiled on July 10 2018
JVM:          1.8.0_241 (Oracle Corporation 25.241-b07)
OS:           Linux 5.12.12-300.fc34.x86_64 amd64
```
 it is

```
* What went wrong:
A problem occurred evaluating script.
> org/gradle/api/plugins/internal/JvmPluginsHelper
```
The first issue was mentioned at https://github.com/freefair/gradle-plugins/issues/53#issuecomment-519773892 but it somehow receded and there was no conclusion. The other one is also unclear to me as the stacktrace says 

```
Caused by: java.lang.NoClassDefFoundError: org/gradle/api/plugins/internal/JvmPluginsHelper
        at io.freefair.gradle.plugins.aspectj.AspectJPlugin.configureSourceSet(AspectJPlugin.java:81)
```

Does it mean that the class was removed or that access to an internal API is blocked? I would like to upgrade the Gradle as much as possible and we could focus on the 2nd case if they are not related. Are you able to help me?

Regards,

Karol.

P.S. I have not tried to isolate the problem but the errors seem so initial that I might be doing something completely wrong here.

**Comment by ksiczek** [comment]
I forgot to attach stacktraces...here you go:
[Gradle_5.0_aspectj.txt](https://github.com/freefair/gradle-plugins/files/6726275/Gradle_5.0_aspectj.txt)
[Gradle_5.4_aspectj.txt](https://github.com/freefair/gradle-plugins/files/6726276/Gradle_5.4_aspectj.txt)

**Comment by larsgrefer** [comment]
Version `5.3.3.3` of the plugin isn't compatible with Gradle `5.x`, that's why you are getting these errors.

Please have a look at the Readme to see which Plugin Versions are made for which Gradle versions: https://github.com/freefair/gradle-plugins#compatibility-matrix

**Comment by ksiczek** [comment]
Thank you @larsgrefer, I have missed the matrix :( I adapted the old plugin but I would like to migrate to something that is maintained so I will give it another try.
