### ISSUE TITLE
can not working on windows

### ISSUE THREAD

**Issue by huangyuzhi** [freefair/gradle-plugins#38]
working on linux system, but can not on windows, and my gradle's version is 5.3.1

**Comment by larsgrefer** [comment]
What's the exact error message?

**Comment by huangyuzhi** [comment]
the generated code does not in build directory, but other directory

**Comment by larsgrefer** [comment]
What exactly are you doing / what do you want to do and what happens instead?

**Comment by huangyuzhi** [comment]
![TIM图片20190412230042](https://user-images.githubusercontent.com/19768989/56046904-e02bc600-5d76-11e9-9ec9-9ceef939f624.png)

the javadoc html file does not generated.
and my OS is windows 10

**Comment by larsgrefer** [comment]
Could you please add the contens of `build/tmp/delombok/delombok.options` here?

**Comment by itarachanka** [comment]
The content of delombok.options file goes below:
--format=pretty
--encoding=UTF-8
--target=C:\Users\tarachenko\git\b-book-boservice\build\delombok\main
--classpath=libs on classpath

If target uses slash (/) as a folder separator for win10, all will work:
--target=C:/Users/tarachenko/git/b-book-boservice/build/delombok/main

**Comment by Favorlock** [comment]
I'm running into this exact same issue with the plugin out of the box. It's not building to the correct folder.

**Comment by Favorlock** [comment]
@larsgrefer I've submitted a pull request that fixes this issue on Win10 based on @itarachanka's suggestion. See #40

**Comment by larsgrefer** [comment]
Maybe @rzwitserloot can help here: Which path separator should be used in delomboks `--target` argument when running on Windows 10?

**Comment by Favorlock** [comment]
My guess is that Lombok requires `/`. I'm pretty sure I saw a delombok folder show up in the build folder, but the delombokked sources were not outputting to that folder and instead result in a folder in the root directory that had the target path as its name. But definitely would be good to get an official say on how Lombok handles it.

**Comment by larsgrefer** [comment]
It seems like https://github.com/rzwitserloot/lombok/blob/150be0a186d880503cb23d056ea4cf229ebc37e5/src/delombok/lombok/delombok/Delombok.java#L352-L436 uses `\` as escape character.

**Comment by larsgrefer** [comment]
Version 3.2.1 should be available from plugins.gradle.org soon.
