### ISSUE TITLE
aspectj version and arguments support

### ISSUE THREAD

**Issue by yefxyz** [freefair/gradle-plugins#39]
Use the official aspectj plugin, you can set aspectjVersion and extra arguments (setAdditionalAjcArgs). It's really useful.

Would you like to add some similar features in the future?

**Comment by larsgrefer** [comment]
The aspectJ version can be customized:

```gradle
aspectj.version = '42'
```
or 
```gradle
aspectj {
    version = '42'
}
```

Which extra argument would you like to set?
