### ISSUE TITLE
Configuration Error: Cannot change dependencies of configuration ':compile' after it has been included in dependency resolution.

### ISSUE THREAD

**Issue by coder6423** [freefair/gradle-plugins#41]
Hi,

I'm running into this problem

> Caused by: org.gradle.api.InvalidUserDataException: Cannot change dependencies of configuration ':compile' after it has been included in dependency resolution.
> 	at io.freefair.gradle.plugins.AspectJCompileTimeWeavingPlugin.lambda$apply$0(AspectJCompileTimeWeavingPlugin.java:23)

The line in question is

>p.getDependencies().add(sourceSet.getCompileConfigurationName(), "org.aspectj:aspectjrt:" + aspectjBasePlugin.getAspectjExtension().getVersion().get())

My project has Spring Boot dependencies in it, and I tried various gradle versions. Any hints what I could look into?

**Comment by larsgrefer** [comment]
Something in you build has already resolved the compile dependencies too early.

Can you share your `build.gradle` or the whole project?

**Comment by coder6423** [comment]
Thanks for your help!

While putting together a minimal example, I found out that removing this line from my config will make it pass:

```
test {
    jvmArgs "-javaagent:${classpath.find { it.name.contains("jmockit") }.absolutePath}"
...
}
```
Any ideas?

**Comment by larsgrefer** [comment]
> jvmArgs "-javaagent:${classpath.find { it.name.contains("jmockit") }.absolutePath}"

This line causes nearly all configurations to be resolved at buildtime. 

You could try using a separate configuration for this:

```
configurations {
    jmockit
}

dependencies {
    jmockit '<jmockitDependencyString>'
}

test {
    jvmArgs "-javaagent:${configurations.jmockit.find { it.name.contains("jmockit") }.absolutePath}"
}
```

**Comment by coder6423** [comment]
Brilliant, thanks a lot! Makes sense now. 

I just had to change the compile config too, otherwise the dependency was missing from the build. So the final configurations block looks like this:

```
configurations {
    jmockit
    compile.extendsFrom(jmockit)
}
```

Thanks for your help and your work on the library!

**Comment by larsgrefer** [comment]
Are you sure you want jmockit in your compile classpath? Shouldn't it be testCompile.extendsFrom() ?
