### ISSUE TITLE
New lombok plugin release? (Java 17)

### ISSUE THREAD

**Issue by dan-lind** [freefair/gradle-plugins#421]
I see that the lombok-plugin was updated to the latest lombok version 1.18.22 about a month ago. This was a quite significant update since it added support for the new Java 17 LTS, but it doesn't look like there are been any subsequent release for the plugin. . Any release planned in the near future?

**Comment by larsgrefer** [comment]
Yes, I've waited for Gradle 7.3 (which also adds Java 17 support)

**Comment by dan-lind** [comment]
Oh, then we have been waiting for the same thing. Good to know, I'll close this.

**Comment by larsgrefer** [comment]
Version 6.3.0 is available now
