### ISSUE TITLE
Support SASS math library

### ISSUE THREAD

**Issue by uvula** [freefair/gradle-plugins#443]
Hi,
I'm very new in the SASS area.
I was playing with Primefaces/Primeflex and found in the documentation "General -> Setup -> Reuse Classes" an example to
create a own "class" (like an alias). So my understanding, I have to compile the Primeflex SASS source to mixin my new class.
https://www.primefaces.org/primeflex/setup

I was looking in my environemnt (Java1.8/Wildfly/Primefaces11/Primeflex3.1.x/Gradle) for a way to compile without
using other sass binaries, so I started with "io.freefair.jsass-war" gradle-plugin.
When I use Primeflex 3.1.0, I can do the example from "Reuse Classes" and mixin my own class in the generated css.

Since 3.1.1 the PFlex developers changed the code and using now a math library.

-- old code using division directly ---
  #{$prop}: #{"rgba(#{$colorValue},#{$shade / 100})"} !important;

-- new code where a math library is now used ---
@use 'sass:math';
....
  #{$prop}: #{"rgba(#{$colorValue},#{math.div($shade, 100)})"} !important;

--

The developers comment in github is:
        DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.
        https://github.com/primefaces/primeflex/issues/81
	
The question is: can "io.freefair.jsass-*" be improved to handle also this "sass:math" library?

Again: my background about SASS is very low.

Uwe

**Comment by Frisch12** [comment]
Hey @uvula, 

Since libsass and jsass are deprecated and no longer supported I am sorry but this cannot be implemented from our side. I think we will deprecate the gradle-plugin as well.

Thank you for reaching out to us and your support.
