### ISSUE TITLE
Question: Does -aspectpath work with Maven BOM in Gradle?

### ISSUE THREAD

**Issue by sangjin-shin-sp** [freefair/gradle-plugins#444]
Using Gradle 7.3.3 and io.freefair.aspectj.post-compile-weaving 6.3.0, can I set aspectpath to an external dependency without specifying the version when using bill of materials?

For example, does this work?
```
dependencies {
  implementation platform('org.foo:bar-bom:1.0.0')
  
  aspect ('org.foo:bar')
}
```

**Comment by larsgrefer** [comment]
Have you tried it?

**Comment by sangjin-shin-sp** [comment]
Yes, but I had to tweak it a bit to make it work:

```
dependencies {
  implementation platform('org.foo:bar-bom:1.0.0')
  aspect platform('org.foo:bar-bom:1.0.0')
  
  aspect ('org.foo:bar')
}
```

It's certainly interesting how this ended up working.
