### ISSUE TITLE
Question: Why can't `io.freefair.aspectj` and `io.freefair.aspectj.post-compile-weaving` be used together?

### ISSUE THREAD

**Issue by huuff** [freefair/gradle-plugins#445]
I apologize if this is a stupid question but I'm fairly new to gradle.

I'm trying to run a project that has some aspects under `src/main/aspectj` and also some main files under `src/main/java`. I'd like to have these aspects compiled and weaved in the classes so I try to use both plugins like:

```groovy
  id "io.freefair.aspectj" version "5.3.0"
  id "io.freefair.aspectj.post-compile-weaving" version "5.3.0"
```

However this gives me: 

```
Failed to apply plugin 'io.freefair.aspectj.post-compile-weaving'.
   > Another aspectj plugin (which is excludes this one) has already been applied to the project.
```

Am I correct in thinking that `io.freefair.aspectj` compiles the aspects and `io.freefair.aspectj.post-compile-weaving` weaves them? If so, why can't they be used together? Is `post-compile-weaving` only intended to work with external aspect libraries? Or is there some way to also weave the compiled aspects with `io.freefair.aspectj`?

**Comment by larsgrefer** [comment]
Having both plugins in one gradle project would be very complex and some configurations would be ambiguous.

If you have annotation-style aspects you can put everything in `src/main/java` and only use the `io.freefair.aspectj.post-compile-weaving` plugin. You can also try to move everything to `src/main/aspectj` and only use the `io.freefair.aspectj` plugin.
A third option is to use 2 subprojects where one depends on the other.

**Comment by huuff** [comment]
Thanks, your answer helped a lot.

I was trying to weave some aspects into some classes from the same project. Using only `post-compile-weaving` as you suggested seemed like a good option but it didn't just work out of the box for me. So I added

```groovy
def aspects = new ArrayList()
fileTree(<package with the aspects>).each {
  aspects.add(it.toString()))
}

compileJava {
  ajc {
    enabled = true
    options {
      compilerArgs = aspects
    }
  }
}
```

I'm sure this is not very good gradle, probably not even good groovy, but it got the job done.
