### ISSUE TITLE
Java 17 compatibility

### ISSUE THREAD

**Issue by xmasux** [freefair/gradle-plugins#446]
I tried using the `post-compile-weaving` plugin with Java 17.
The project I am working on uses the required specs like defined in your compatibility matrix: 
Plugin Version: 6.3.0
Gradle Version: 7.3
Java Version: 17

However when executing `compileJava` in the sub-project which applies the `post-compile-weaving` plugin the following error occurs:
`[error] target level should be in '1.1'...'1.8','9'...'14': 17`

From my understanding of this message the problem is that the plugin does not correctly work with Java 17.
When I downgrade the Java version, of the sub-project using the plugin, to 11 everything works like expected.

**Comment by xmasux** [comment]
Update: So my guess is that the plugin is not yet compatible with Java 17

I created a test repo here: https://github.com/xmasux/aspectj-sample.git

**Comment by larsgrefer** [comment]
You are using AspectJ 1.9.7 which only supports Java 16. For Java 17 support you have to update to 1.9.8.RC3
