### ISSUE TITLE
[AspectJ] Not support third party jars ?

### ISSUE THREAD

**Issue by liuqingdada** [freefair/gradle-plugins#450]
gradle version: distributionUrl=https\://services.gradle.org/distributions/gradle-5.6.4-all.zip

build.gradle:
```
apply plugin: 'java'
apply plugin: "io.freefair.aspectj.base"
apply plugin: "io.freefair.aspectj.post-compile-weaving"
apply plugin: 'org.jetbrains.kotlin.jvm'
apply plugin: 'org.jetbrains.kotlin.kapt'
apply from: "${rootDir}/build.gradle"

buildscript {
    apply from: "${rootDir}/ext.gradle"

    repositories {
        mavenCentral()
        maven {
            url "https://plugins.gradle.org/m2/"
        }
    }

    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:${versions.kotlin}"
        classpath "io.freefair.gradle:aspectj-plugin:5.3.3.3"
    }
}

sourceCompatibility = 1.8
targetCompatibility = 1.8

repositories {
    mavenCentral()
}

sourceSets {
    main {
        kotlin {
            srcDirs = ['src/main/java', 'src/main/kotlin', 'src/main/netty']
        }
        java {
        }
    }
}

kapt {
    useBuildCache = true
}

dependencies {
    implementation fileTree(dir: "libs", include: ["*.jar"])
    compile "io.netty:netty-all:${versions.nettyAll}"
    compile "org.jetbrains.kotlin:kotlin-reflect"
    compile "org.jetbrains.kotlin:kotlin-stdlib"
    compile "org.jetbrains.kotlin:kotlin-stdlib-jdk7"
    compile "org.jetbrains.kotlin:kotlin-stdlib-jdk8"
    testCompile group: 'junit', name: 'junit', version: '4.12'
    testCompile "org.jetbrains.kotlin:kotlin-test"
    testCompile "org.jetbrains.kotlin:kotlin-test-junit"

    implementation "io.reactivex.rxjava2:rxjava:2.2.15"
    implementation "com.squareup.okhttp3:okhttp:4.2.2"
    implementation "org.apache.poi:poi:4.1.1"
    implementation "org.apache.poi:poi-ooxml:4.1.1"
    implementation "dom4j:dom4j:1.6.1"
    implementation 'org.jboss.windup.decompiler:decompiler-fernflower:5.2.1.Final'
    implementation 'org.aspectj:aspectjrt:1.9.6'
    implementation 'org.aspectj:aspectjweaver:1.9.6'
}

compileKotlin {
    kotlinOptions.jvmTarget = "1.8"
}
compileTestKotlin {
    kotlinOptions.jvmTarget = "1.8"
}
```

It works in project java file:
AnnoAspect.java:
```
@Aspect
public class AnnoAspect {

    @Pointcut("execution(* com.shengsiyuan.aspect.App.say(String, String))")
    public void jointPoint(JoinPoint joinPoint) {
    }

    @Before("jointPoint(joinPoint)")
    public void before(JoinPoint joinPoint) {
        Object[] args = joinPoint.getArgs();
        System.out.println("AnnoAspect before say: " + args[0] + args[1]);
    }

    @After("jointPoint(joinPoint)")
    public void after(JoinPoint joinPoint) {
        Object[] args = joinPoint.getArgs();
        System.out.println("AnnoAspect after say: " + args[0] + args[1]);
    }

}
```

App.java:
```
public class App {

    public void say(String hello, String world) {
        System.out.println("App say: " + hello + world);
    }

    public static void main(String[] args) {
        App app = new App();
        app.say("hello", " world");
    }
}
```

but, when I joint point to third jar class file:

ImportCollectorAspect.java:
org.jetbrains.java.decompiler.main.collectors.ImportCollector at 'org.jboss.windup.decompiler:decompiler-fernflower:5.2.1.Final' jar file
```
@Aspect
public class ImportCollectorAspect {

    @Pointcut("execution(* org.jetbrains.java.decompiler.main.collectors.ImportCollector.getShortName(String, boolean))")
    public void jointPoint(JoinPoint joinPoint) {
    }

    @Before("jointPoint(joinPoint)")
    public void before(JoinPoint joinPoint) {
        Object[] args = joinPoint.getArgs();
        System.out.println("ImportCollectorAspect before: " + args[0] + args[1]);
    }

    @After("jointPoint(joinPoint)")
    public void after(JoinPoint joinPoint) {
        Object[] args = joinPoint.getArgs();
        System.out.println("ImportCollectorAspect after: " + args[0] + args[1]);
    }
}
```

gradle warnning:
/Users/yangliuqing/work/github/ShengSiYuan/kotlin/basic/build/classes/java/test!com/shengsiyuan/aspect/ImportCollectorAspect.class [warning] advice defined in com.shengsiyuan.aspect.ImportCollectorAspect has not been applied [Xlint:adviceDidNotMatch]

project address:
https://github.com/liuqingdada/ShengSiYuan/tree/release_old_aspectj/kotlin/basic

On the other hand:
when I use io.freefair.aspectj plugin rather than io.freefair.aspectj.post-compile-weaving.
AnnoAspect  and  ImportCollectorAspect  all not working.

 

如果能帮忙解决，万分感激！！

**Comment by larsgrefer** [comment]
The weaving works by actually modifying the bytecode of the classes. This is not easily possible for external jars.

You can try to declare the external dependency not as `implementation` but as `inpath` dependency. This will pass the dependency as `-inpath` to the ajc so that you project will then contain the modified bytecode from the jar file.

Another option would be to use load-time-weaving, so the bytecode of the external jar can be modified on the fly, when the classes are loaded into the JVM: https://www.eclipse.org/aspectj/doc/released/devguide/ltw.html

**Comment by liuqingdada** [comment]
>

**Comment by liuqingdada** [comment]
> The weaving works by actually modifying the bytecode of the classes. This is not easily possible for external jars.
> 
> You can try to declare the external dependency not as `implementation` but as `inpath` dependency. This will pass the dependency as `-inpath` to the ajc so that you project will then contain the modified bytecode from the jar file.
> 
> Another option would be to use load-time-weaving, so the bytecode of the external jar can be modified on the fly, when the classes are loaded into the JVM: https://www.eclipse.org/aspectj/doc/released/devguide/ltw.html

I changed implementation to inpath, but it still not working.
The error is below:
```
/Users/yangliuqing/work/github/ShengSiYuan/kotlin/basic/build/classes/java/test!com/shengsiyuan/aspect/ImportCollectorAspect.class [warning] advice defined in com.shengsiyuan.aspect.ImportCollectorAspect has not been applied [Xlint:adviceDidNotMatch]
```
And the gradle config is below:
```

dependencies {
    inpath fileTree(dir: "libs", include: ["*.jar"])
    compile "io.netty:netty-all:${versions.nettyAll}"
    compile "org.jetbrains.kotlin:kotlin-reflect"
    compile "org.jetbrains.kotlin:kotlin-stdlib"
    compile "org.jetbrains.kotlin:kotlin-stdlib-jdk7"
    compile "org.jetbrains.kotlin:kotlin-stdlib-jdk8"
    testCompile group: 'junit', name: 'junit', version: '4.12'
    testCompile "org.jetbrains.kotlin:kotlin-test"
    testCompile "org.jetbrains.kotlin:kotlin-test-junit"

    implementation "io.reactivex.rxjava2:rxjava:2.2.15"
    implementation "com.squareup.okhttp3:okhttp:4.2.2"
    implementation "org.apache.poi:poi:4.1.1"
    implementation "org.apache.poi:poi-ooxml:4.1.1"
    implementation "dom4j:dom4j:1.6.1"
//    implementation 'org.jboss.windup.decompiler:decompiler-fernflower:5.2.1.Final'
    implementation 'org.aspectj:aspectjrt:1.9.5'
    implementation 'org.aspectj:aspectjweaver:1.9.5'
}
```

**Comment by larsgrefer** [comment]
What jars do you have in the lib dir?

**Comment by liuqingdada** [comment]
> What jars do you have in the lib dir?
It is decompiler-fernflower jar,  jetbrain official jar package

**Comment by larsgrefer** [comment]
Can you provide an example project, so I can reproduce this myself?

**Comment by larsgrefer** [comment]
I see your aspect is defined in the `test` source set. That is why the `inpath` does not work.

For aspectJ in unit-tests you can use `testInpath`

**Comment by liuqingdada** [comment]
> 

It is works for `io.freefair.aspectj.post-compile-weaving` plugin, Thank you so much! 谢谢哥哥！！！

But when I use `io.freefair.aspectj` plugin, it is not working. I have upload the code to sample project.

**Comment by larsgrefer** [comment]
With the `io.freefair.aspectj` plugin you have to be even more careful, which classes are when compiled/processed by ajc.

Both the aspect itself and the targeted classes must be processed by ajc at least once.
And the aspect must be already present when the targeted classes are processed.

Have a look at https://github.com/freefair/gradle-plugins/tree/master/examples/aspectj for some usage examples

**Comment by liuqingdada** [comment]
> With the `io.freefair.aspectj` plugin you have to be even more careful, which classes are when compiled/processed by ajc.
> 
> Both the aspect itself and the targeted classes must be processed by ajc at least once. And the aspect must be already present when the targeted classes are processed.
> 
> Have a look at https://github.com/freefair/gradle-plugins/tree/master/examples/aspectj for some usage examples

Thank you so much，tank you!
