### ISSUE TITLE
aspectj does nothing

### ISSUE THREAD

**Issue by p-a-w-e-l** [freefair/gradle-plugins#455]
Hello!
I wanted to replace a deprecated uphyca plugin which **works** with the old gradle.

I have updated gradle plugin to version 7.0.4 and gradle to version 7.3.3 (tried 7.3 too).
In the main module, in build.gradle, I added:

```	
dependencies {
    classpath "io.freefair.gradle:aspectj-plugin:6.3.0"
    ...
}
repositories {
    maven {
        url "https://plugins.gradle.org/m2/"
     }
    google ()
    mavenCentral ()
 }
```

In the module with .aj file, in build.gradle, I inserted line:
`apply plugin: 'io.freefair.aspectj'`

I created the main.aspectj directory and moved the .aj file there (the found ways to set the path do not work, because aspectj has no properties given there).

As a result, aspect code stopped working.

How to get the freefair.aspectj plugin to work? Can something be turned on in Android Studio so that the freefair.aspectj plugin will display in build output if is working, where does it look for and if it find the .aj file?

**Comment by larsgrefer** [comment]
Can you provide an example project so I can see what exactly you are trying to do?

**Comment by p-a-w-e-l** [comment]
It's a huge (MultiDex), commercial project and I cannot present anything sensible in a micro.

Is the plugin leave somewhere any traces, or can I turn on any logging? Now I only see the .aj file copied to intermediates\java_res\debug\out\main\aspectj\

**Comment by larsgrefer** [comment]
I think I now understand your problem.

The `io.freefair.aspectj` plugin is not designed to be used with an android project. It is made for "normal" java projects.

For android projects there is a separate plugin: https://plugins.gradle.org/plugin/io.freefair.android.aspectj.post-compile-weaving
