### ISSUE TITLE
gradle 2.x Compatibility

### ISSUE THREAD

**Issue by joshua-hw** [freefair/gradle-plugins#47]
hello, is there any version Compatibilitable with gradle 2.x

**Comment by larsgrefer** [comment]
Only version 0.0.1 was targeted at Gradle 2.x.

**Comment by joshua-hw** [comment]
> Only version 0.0.1 was targeted at Gradle 2.x.

Hey, the oldest version I found here : https://plugins.gradle.org/m2/io/freefair/gradle/aspectj-plugin/ is 2.5.10

**Comment by joshua-hw** [comment]
> Only version 0.0.1 was targeted at Gradle 2.x.

Tks, I'll upgrade my gradle version and try newer version of this plugin.
