### ISSUE TITLE
Git-version task : Use commit SHA as project version 

### ISSUE THREAD

**Issue by elvay1** [freefair/gradle-plugins#472]
Hello this issue is an improvement proposal: 

I would like to be able to use the commit SHA as project version instead of <BRANCH_NAME>-SNAPSHOT pattern.
Is it something suitable for this plugin? If it's ok I can work on  this subject and provide a PR when it's done.

**Comment by larsgrefer** [comment]
Just using the SHA-Hash should be very easy:

```gradle
def sha = "git rev-parse --short HEAD".execute().text
allprojects { version = sha }
```

**Comment by elvay1** [comment]
The behaviour I want is : when there is a commit tag, project version is the tag number, otherwise it is the commit sha (or a concatenation of the branch name with short sha) in order to prevent use of changing version.
I started a fork implementing this kind of feature (and of course keeping the branch-SNAPSHOT pattern by default), it also adds gitlab CI support. I would understand if this is not the kind of feature you want in freefair plugin, just take it as a proposal!

**Comment by Frisch12** [comment]
@elvay1 You can create a PR every time you want. We will have a look over it and decide if it is suitable for this gradle-plugin-collection. 
I think it would be a nice plugin. However I think it would be better/easier to implement it as a ci step like this for GitHub-actions:
```
- name: Create version number
  shell: bash
  run: |
    VERSION_NUMBER="${{ github.sha }}"
    echo "##[set-output name=version_number;]$VERSION_NUMBER"
```

And then in case of deployment (in this case docker) just retag:
```
- name: Retag docker image (also verifies that backend image to deploy exists for branch)
  shell: bash
  run: |
    IMAGE_NAME="ghcr.io/${{ github.repository }}/my-nice-image"
    CURRENT_TAG="${{ github.event.inputs.hash }}"
    NEW_TAG="${{ github.event.inputs.tag }}"
    # pull, tag, push
    docker pull ${IMAGE_NAME}:${CURRENT_TAG}
    docker tag ${IMAGE_NAME}:${CURRENT_TAG} ${IMAGE_NAME}:${NEW_TAG}
    docker push ${IMAGE_NAME}:${NEW_TAG}
```
