### ISSUE TITLE
post-compile weaving .class in jar

### ISSUE THREAD

**Issue by joshua-hw** [freefair/gradle-plugins#48]
in my project, module `xxx-api` depends on `xxx-core`,`xxx-core` depends on `httpcore-nio`, I write a .aj file which will change bytecode of a .class file in `httpcore-nio.jar`. will these codes in build.gradle work?

```
project(":xxx-api") {

    dependencies {
        aspect project(":xxx-core")
    }

    compileJava {
        ajc {
            enabled = true
            compilerArgs = ["-sourceroots src/main/java/com/xxx/xxx/xxx/core/client/https/aop/"]
        }
    }
}

**Comment by larsgrefer** [comment]
Is `httpcore-nio` a module of your project or are you referring to `org.apache.httpcomponents:httpcore-nio`?

If it's a module of your project, you should apply the weaving there.
If it's an external jar, you would need to use the `-inpath` argument of ajc.

**Comment by joshua-hw** [comment]
> Is `httpcore-nio` a module of your project or are you referring to `org.apache.httpcomponents:httpcore-nio`?
> 
> If it's a module of your project, you should apply the weaving there.
> If it's an external jar, you would need to use the `-inpath` argument of ajc.

it's `org.apache.httpcomponents:httpcore-nio`. I still have these questions
1. should `compileJava` be written in `project(":xxx-api")` or `project(":xxx-core")`
2. is it right? `compilerArgs = ["-inpath httpcore-nio-4.4.6.jar"]`

**Comment by larsgrefer** [comment]
At the moment it's a bit tricky to configure this, but I think I can enhance the plugins to make this a bit easier.

**Comment by joshua-hw** [comment]
That will be so cool. I'm sure many other people need this feature 👍
