### ISSUE TITLE
compileSass - SassCompilationFailedException: Error: Can't find stylesheet to import.

### ISSUE THREAD

**Issue by teemukin65** [freefair/gradle-plugins#512]
Using 
 plugin: "io.freefair.sass-webjars"  `
in my `build.gradle` as follows: 
```
buildscript { 
...
      dependencies {
...
           classpath "io.freefair.gradle:embedded-sass-plugin:6.4.2"
}
...
 apply plugin: "io.freefair.war-overlay"
apply plugin: "war"
apply plugin: "org.springframework.boot"
apply plugin: "io.freefair.lombok"
apply plugin: "io.freefair.sass-java"
apply plugin: "io.freefair.sass-webjars"
...
sass {
    sourceMapEnabled = true
    outputStyle = EXPANDED
}
compileSass {
}
...
dependencies {
... multitude of other implementation & compilation etc. dependencies...
      implementation 'org.webjars:bootstrap:5.1.3'
}
```
Then in my .sass - file I have reference to the bootstrap - CSS library: 
`@import "bootstrap/scss/bootstrap";`
But gradle build fails: 

> 
> Execution failed for task ':compileSass'.
> > de.larsgrefer.sass.embedded.SassCompilationFailedException: Error: Can't find stylesheet to import.
>     ╷
>   6 │ @import "bootstrap/scss/bootstrap";
>     │         ^^^^^^^^^^^^^^^^^^^^^^^^^^
>     ╵
>     src/main/resources/static/css/cas.scss 6:9  root stylesheet

Java v. 11
gradle version: Gradle 7.4.2

Is this a bug , because the reference is just as instructed in [plugin docs](https://docs.freefair.io/gradle-plugins/6.4.2/reference/#_io_freefair_sass_webjars ) IMHO.    Or how to define the compileSass - resources correctly ?

**Comment by larsgrefer** [comment]
Our documentation is indeed wrong here.

The import should be one of those:

```scss
@import "bootstrap/5.1.3/scss/bootstrap";
@import "5.1.3/scss/bootstrap";
@import "scss/bootstrap";
```

**Comment by teemukin65** [comment]
Thanks a lot! That helped!
