### ISSUE TITLE
Can't pre-populate fields on MavenJava Publication until after plugin is applied

### ISSUE THREAD

**Issue by loosebazooka** [freefair/gradle-plugins#52]
Would it make sense to check for existence of publication before creating one?
should
https://github.com/freefair/gradle-plugins/blob/b0881c698b540088250f30f46c47dc44c5e4d151/maven-plugin/src/main/java/io/freefair/gradle/plugins/maven/MavenPublishBasePlugin.java#L29-L31

become (something like)
```java
PublicationContainer publications = 
    project.getExtensions().getByType(PublishingExtension.class).getPublications()
publication = publications.findByName(getPublicationName())
if (publication == null) {
  publication = publications.create(getPublicationName(), MavenPublication.class)
}
```

**Comment by larsgrefer** [comment]
What exactly is your use case?

It's the purpose of the plugin (`io.freefair.maven-publish-java`) to create the `mavenJava` configuration. Therefore you can't configure it before it was created by the plugin.

**Comment by loosebazooka** [comment]
Oops, I should've closed this. I was trying to share some pom configuration but ended up doing it as a callback.

**Comment by larsgrefer** [comment]
Just put an `apply plugin: 'io.freefair.maven-publish-java'` before accessing the `mavenJava` publication and you should be fine.

**Comment by loosebazooka** [comment]
Yeah so in a multimodule project, it's a little less straight forward when only one artifact is a maven plugin. I used callback incorrectly, what I mean was just a regular method call in the child project that is defined in the parent.

**Comment by larsgrefer** [comment]
In this case something like this should work:

```groovy
subprojects {
    plugins.withId("io.freefair.maven-publish-java") {
        publications.mavenJava {
            // ...
        }
    }
}
```

Note that the `io.freefair.maven-publish-java` plugin can also be used independently of the `io.freefair.maven-plugin` plugin.

**Comment by loosebazooka** [comment]
Right, another valid mechanism, but I'm sharing pom config with other projects and I don't want my parent to know about subprojects. Either way, I think I have this figured out. Thanks for the workarounds.
