### ISSUE TITLE
Delombok does not support Gradle toolchains

### ISSUE THREAD

**Issue by Fiouz** [freefair/gradle-plugins#533]
# Context

Gradle 7.4.2 build relying on the [toolchain](https://docs.gradle.org/current/userguide/toolchains.html) feature to compile with a different JDK than the one running Gradle itself.

<details><summary>build.gradle.kts</summary>

```kotlin
plugins {
    id("java-library")
    id("io.freefair.lombok") version "6.4.3"
}

group = "org.example"
version = "1.0-SNAPSHOT"

repositories {
    mavenCentral()
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(8))
    }
}
```

</details>

<details><summary>src/main/java/org/example/Main.java</summary>

```java
package org.example;

import lombok.var;

public class Main {
    public static void main(String[] args) {
        var toto = "Hello world!";
        System.out.println(toto);
    }
}
```
</details>

<details><summary>Output of the :javaToolchains task</summary>

```
> Task :javaToolchains

 + Options
     | Auto-detection:     Enabled
     | Auto-download:      Enabled

 + Eclipse Temurin JDK 1.8.0_332-b09
     | Location:           C:\Program Files\Eclipse Adoptium\jdk-8.0.332.9-hotspot
     | Language Version:   8
     | Vendor:             Eclipse Temurin
     | Architecture:       amd64
     | Is JDK:             true
     | Detected by:        environment variable 'JDK8_HOTSPOT'

<trimmed down for brevity>

 + IBM JDK 17.0.3+7
     | Location:           C:\Program Files\Semeru\jdk-17.0.3.7-openj9
     | Language Version:   17
     | Vendor:             IBM
     | Architecture:       amd64
     | Is JDK:             true
     | Detected by:        Current JVM

```
</details>

- JDK used for running Gradle: JDK 17
- JDK used for compiling: JDK 8

# Affected feature

`delombok` / `io.freefair.gradle.plugins.lombok.tasks.Delombok` task

# Expected behavior

Able to _delombok_ the code without issue.
If it's not possible to automatically infer which toolchain to use, there should be a way for the user to select the toolchain `Delombok` will use.

# Actual behavior

- Delombok outputs an error message, seemingly because it used the wrong JDK
```
gradlew delombok --rerun-tasks

> Task :delombok
C:\Users\Fiouz\Projects\lombok-testing\src\main\java\org\example\Main.java:3: error: illegal reference to restricted type 'var'
import lombok.var;
             ^

BUILD SUCCESSFUL in 3s
1 actionable task: 1 executed
```

(the obvious underlying issue is that `var` is a keyword in newer Java versions)

- Despite the error, Gradle still reports success. It seems related to https://github.com/freefair/gradle-plugins/blob/6.4.3/lombok-plugin/src/main/java/io/freefair/gradle/plugins/lombok/tasks/Delombok.java#L198-L209 not processing the [`javaexec` return value](https://docs.gradle.org/current/javadoc/org/gradle/process/ExecOperations.html#javaexec-org.gradle.api.Action-)

(it should be noted that `.java` files are still generated under `build/generated/sources/delombok`, but it is still concerning that the Gradle task does not check the output of the execution)

**Comment by larsgrefer** [comment]
Thanks for the details report 👍 

Supporting toolchains for (de)lombok is a good idea.

The problem with the successful build is, that the delombok process actually exits with 0: `{exitValue=0, failure=null}`
