### ISSUE TITLE
Missing API documentation https://docs.freefair.io/gradle-plugins/current/api

### ISSUE THREAD

**Issue by Fiouz** [freefair/gradle-plugins#534]
https://docs.freefair.io/gradle-plugins/current/api, referenced from https://docs.freefair.io/gradle-plugins/current/reference/, returns a 404 HTTP error code.

**Comment by larsgrefer** [comment]
Thanks for bringing this to my attention. There was a error in the javadoc generation.

For the current SNAPSHOT, the javadoc is now available again https://docs.freefair.io/gradle-plugins/master-SNAPSHOT/api/

the "_current_" link, will be fixed by the next release
