### ISSUE TITLE
Lombok Config Block Deprecation / Removal

### ISSUE THREAD

**Issue by austinarbor** [freefair/gradle-plugins#556]
Hello,
It looks like the Lombok config block was deprecated and then subsequently removed in the latest version of the plugin. Is the recommended replacement to put these values in the lombok.config files instead?

Thanks

**Comment by larsgrefer** [comment]
Exactly. Just edit/provide the lombok.config files yourself.

**Comment by austinarbor** [comment]
Thanks!
