### ISSUE TITLE
Kotlin 1.7.0 Compliance level is incompatible 

### ISSUE THREAD

**Issue by niqo01** [freefair/gradle-plugins#559]
When upgrading my project from Kotlin 1.6.21 to 1.7.0 I am getting the following error:
```
> Task :app:api:compileKotlin FAILED
[error] Compliance level '1.4' is incompatible with target level '11'. A compliance level '11' or better is required
```
Disabling the aspectj plugin solve the issue.

I am using `io.freefair.aspectj.post-compile-weaving:6.5.0.2`

Here is a link to the Gradle build file used:
https://github.com/niqo01/social-cats-playground/blob/nm/testCdkPipeline/test-cdk-pipeline/app/api/build.gradle.kts

**Comment by larsgrefer** [comment]
Thanks for the example project, this was very helpful.

You should be able to use this workaround until a new version of this plugin is available:

```gradle
tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile> {
    kotlinOptions.jvmTarget = "11"
    configure<io.freefair.gradle.plugins.aspectj.AjcAction> {
        options.compilerArgs.add("-source")
        options.compilerArgs.add("11")
    }
}
```
