### ISSUE TITLE
Missing Plantuml plugin docs

### ISSUE THREAD

**Issue by kkocel** [freefair/gradle-plugins#580]
I would like to know how to configure the Plant UML plugin. 
Readme is empty: https://github.com/freefair/gradle-plugins/blob/master/plantuml-plugin/README.md
same as https://plugins.gradle.org/plugin/io.freefair.plantuml
and https://docs.freefair.io/gradle-plugins/current/reference/

**Comment by Frisch12** [comment]
Hey @kkocel, 
Thank you for your issue. You are right the documentation was missing for this plugin.
I've just created a rudimentary documentation.

**Comment by kkocel** [comment]
Thanks, will https://docs.freefair.io/gradle-plugins/current/reference/ be populated after release?
