### ISSUE TITLE
Lombok gradle plugin does not return correct object when using a generic class with builder()

### ISSUE THREAD

**Issue by jsimone-infoarmor** [freefair/gradle-plugins#581]
We found a possible bug in the freefair Lombok plugin for gradle.  We were using 6.4.3 but the bug seems to be in the latest code as well.
We use Java 11 and Gradle 7.4.2.
 
The bug is this:
 
This builder pattern works with this code just fine:
```java
   Event alertProcessedEvent = Event.builder()
            .type(KafkaEventType.ALERT_PROCESSED.getType())
            .version(KafkaEventType.ALERT_PROCESSED.getVersion())
            .topic(KafkaTopic.IDENTITY_MONITORING)
            .body(alertProcessedEventBody)
            .build();
```

Where Event is this:
```java
@Builder
@Setter
@Getter
@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
public class Event {
    private String type;
    private int version;
    private String topic;
    private AlertProcessedEventBody body;
}
```

But fails with this generic usage:
```java
   Event<AlertProcessedEventBody> alertProcessedEvent = Event.builder()
            .type(KafkaEventType.ALERT_PROCESSED.getType())
            .version(KafkaEventType.ALERT_PROCESSED.getVersion())
            .topic(KafkaTopic.IDENTITY_MONITORING)
            .body(alertProcessedEventBody)
            .build();
```

Where Event is this generic form:
```java
@Builder
@Setter
@Getter
@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
public class Event < T > {
    private String type;
    private int version;
    private String topic;
    private T body;
}
```

Builder()…build() returns. Event<Object> instead of Event<AlertProcessedEventBody> and intellij won’t compile it.

**Comment by larsgrefer** [comment]
Have you tried calling it like this?:

```java
Event<AlertProcessedEventBody> alertProcessedEvent = Event.<AlertProcessedEventBody>builder().build();
```

**Comment by jsimone-infoarmor** [comment]
That worked. Thanks.  I have not seen that “dot” construct before.
joe

From: Lars Grefer ***@***.***>
Date: Thursday, August 18, 2022 at 5:54 PM
To: freefair/gradle-plugins ***@***.***>
Cc: Joseph Simone ***@***.***>, Author ***@***.***>
Subject: Re: [freefair/gradle-plugins] Lombok gradle plugin does not return correct object when using a generic class with builder() (Issue #581)
Have you tried calling it like this?: Event<AlertProcessedEventBody> alertProcessedEvent = Event. <AlertProcessedEventBody>builder(). build(); — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving
ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
This message came from outside your organization.
ZjQcmQRYFpfptBannerEnd

Have you tried calling it like this?:

Event<AlertProcessedEventBody> alertProcessedEvent = Event.<AlertProcessedEventBody>builder().build();
