### ISSUE TITLE
Unable to delombok directory with spaces in it

### ISSUE THREAD

**Issue by twistedtwin** [freefair/gradle-plugins#65]
Unable to run delombok task on a project directory with spaces in the name.  Renaming the project directory without spaces allows the task to run.

When running the delombok task on a directory with spaces, the following message is displayed:
> Task :delombok
WARNING: does not exist - skipping: /Users/someuser/Repos/Github/delombok-spaces/with spaces/spaces/build/delombok/main

Example projects with and without spaces are here:
https://github.com/twistedtwin/delombok-spaces

**Comment by larsgrefer** [comment]
@twistedtwin Thanks for providing the example project. This was really helpful.

**Comment by larsgrefer** [comment]
This should now be fixed in `3.8.2`

**Comment by twistedtwin** [comment]
Verified in the example projects that it's working in 3.8.2.  Thanks.
