### ISSUE TITLE
Update PlantUML version to latest (1.2023.1)

### ISSUE THREAD

**Issue by JakubLedworowski** [freefair/gradle-plugins#713]
https://mvnrepository.com/artifact/net.sourceforge.plantuml/plantuml/1.2023.1

**Comment by larsgrefer** [comment]
This already happened in #697 fd379c3e75116b6a5bf7e45e80a3b42313bf7585

**Comment by JakubLedworowski** [comment]
Hi, thanks for your reply. I see that it was updated, however gradle consistently downloads the version 1.2022.5.jar:
![image](https://user-images.githubusercontent.com/77668277/219582632-76fe2222-bd38-48fe-935e-5ce8f8a4bf79.png)

even if I use plugin in latest version 6.6.2
![image](https://user-images.githubusercontent.com/77668277/219582826-7d7f7fe6-5223-41c8-a1b7-82b2fd0367eb.png)

Are you able to reproduce this?
I use the plugin as in the example https://github.com/freefair/gradle-plugins/blob/master/examples/plantuml/build.gradle

**Comment by JakubLedworowski** [comment]
It worked, thank you :)
