### ISSUE TITLE
Upgrading to Gradle 8.0.2 is failing because using @SkipWhenEmpty has been deprecated

### ISSUE THREAD

**Issue by cv-prasad** [freefair/gradle-plugins#757]
As per the upgradation [documentation](https://docs.gradle.org/current/userguide/upgrading_version_7.html) we were trying to move to gradle latest version but were facing issues. Suggested solution was to not have @SkipWhenEmpty on filteredInput(). We tried work arounds but it failed. Need help on this.
The build deprecation shown is as below
`Relying on FileTrees for ignoring empty directories when using @SkipWhenEmpty has been deprecated.Annotate the property filteredInput with @IgnoreEmptyDirectories or remove @SkipWhenEmpty.`
We are not using Propery in java code, entire configuration is in build.gradle
[link](https://docs.gradle.org/7.5/userguide/upgrading_version_7.html#empty_directories_file_tree) to handling empty directories from gradle upgradation documentation.
Can @SkipWhenEmpty be removed for filteredInput from [here](https://github.com/freefair/gradle-plugins/blob/master/lombok-plugin/src/main/java/io/freefair/gradle/plugins/lombok/tasks/Delombok.java#L129)

**Comment by cv-prasad** [comment]
@larsgrefer can you please help. If any work-arounds please suggest. Thanks in advance

**Comment by larsgrefer** [comment]
This version is nearly two years old and was developed for Gradle 6.7.

Please try again with version 8.0.1
