### ISSUE TITLE
[aggregate-javadoc] javadoc options not taken into account

### ISSUE THREAD

**Issue by vratojr** [freefair/gradle-plugins#76]
Hello, I'm using gradle 4.10 and "io.freefair.aggregate-javadoc" version "2.9.5".
I'm passing specific taglet options to the javadoc task of the parent projet:
```
javadoc {
    options {
        tagletPath = configurations.javadocTaglets.files as List
        taglets = ["org.jdrupes.taglets.plantUml.Taglet"]
    }
}
```
And this options are not taken into account nor propagated to the subprojects (the taglet is not used).
If I use the javadoc task alone, the taglet is correctly used.

**Comment by larsgrefer** [comment]
If you want this configuration to be applied for all Javadoc tasks you could try something like this:

```gradle
allprojects {
    tasks.withType(Javadoc) {
        options {
            tagletPath = configurations.javadocTaglets.files as List
            taglets = ["org.jdrupes.taglets.plantUml.Taglet"]
        }
    }
}
```

**Comment by vratojr** [comment]
It works, thanks!
