### ISSUE TITLE
Is Groovy/Grails not fully supported? (compiler limitation) warning

### ISSUE THREAD

**Issue by tucker-bluesage** [freefair/gradle-plugins#794]
I was trying out the Gradle plugin:
```
id "io.freefair.aspectj.post-compile-weaving" version "6.2.0" //and 5.3.3.3
```
Hoping to avoid the issue with proxies but I get the following warning:
```
 [warning] Only before advice is supported on handler join points (compiler limitation)
```

I tried on Grails 4.1.1/Gradle 6.9/Groovy 2.5 and Grails 5.3.2/Gradle 7.2/Groovy 3.0.11

**Comment by larsgrefer** [comment]
What advice are you trying to weave to what JoinPoints?

**Comment by tucker-bluesage** [comment]
I was trying to do something like this:
```
+
+import groovy.transform.CompileStatic
+import groovy.util.logging.Slf4j
+import org.aspectj.lang.JoinPoint
+import org.aspectj.lang.annotation.*
+
+@Aspect
+@Slf4j
+@CompileStatic
+class LoggingAspect {
+
+    @Pointcut("!within(somepackage.SomeService) && !within(somepackage.SomeControllerController) && !within(somepackage.SomeOtherService)  && within(somepackage.*) && !execution(* somepackage.*.getMetaClass(..))")
+    void logPointcutWithin() {
+    }
+
+    @Before("logPointcutWithin()")
+    void logMethodCallsWithinAdvice(JoinPoint joinPoint) {
+        log.info("In Before  Aspect at " + joinPoint.getSignature().toString())
+    }
+
+    @After("logPointcutWithin()")
+    void logMethodCallsAfterAdvice(JoinPoint joinPoint) {
+        log.info("In After  Aspect at " + joinPoint.getSignature().toString())
+    }
+//
+//    @AfterThrowing(value = "logPointcutWithin()", throwing = "ex")
+//    void logMethodCallsAfterThrowingAdvice(JoinPoint joinPoint, Exception ex) {
+//        log.info("Exception After  Aspect at " + joinPoint.getSignature().toString(), ex)
+//    }
+}
```
The idea was to have the ability to log on entry/exit of a method and on exception to help debugging because one of my coworkers has the "brilliant" idea to put logging and try/catch blocks in every method in a big code base. My coworker went ahead with that plan anyway and eventually had to roll some of it back because there were too many logs making it hard to debug... who could have seen that coming. The thought of using aspects was also so that we could potentially make this configurable and be able to turn it on and off if we didn't need the extra logging.

I eventually abandoned this because I also found that the Gradle plugin conflicted with a Grails gradle plugin, so I couldn't get it working, and using the Spring version has the proxy issue, i.e. internal calls in a class don't get picked up. This wasn't really my project anyway, I was just the only one who pushed back at the idea of putting try/catches everywhere.

Thanks for eventually getting back to me, I had forgotten about this.
