### ISSUE TITLE
Lombok is outdated

### ISSUE THREAD

**Issue by Desoroxxx** [freefair/gradle-plugins#898]
Hi, I recently updated my project to Java 21 and saw an error related to Lombok, I looked through Lombok's issues and it appear to have been fixed in 1.18.30, so I looked here, and it appears that Lombok was up to date, which left me even more confused.

After looking in my `External Libraries` section of my IDE I noticed that Lombok was using version 1.18.28, which confused me even more. So, I decided to clear my Gradle cache and after redownloading everything, it was still the same.

It appears this plugin is downloading the wrong Lombok version some way or another.

I am using version `8.3` of the Lombok plugin.

**Comment by larsgrefer** [comment]
Lombok already has been updated in #892 which will be part of version 8.4.

In the meantime, you can override the Lombok version as described here: https://docs.freefair.io/gradle-plugins/8.3/reference/#_io_freefair_lombok_base

**Comment by larsgrefer** [comment]
Version 8.4 has been released by now, so this should be fixed.
