### ISSUE TITLE
Update Compatibility Matrix

### ISSUE THREAD

**Issue by McPringle** [freefair/gradle-plugins#928]
Please update the [Compatibility Matrix](https://github.com/freefair/gradle-plugins#compatibility-matrix) in the README file, it stops with v8.0.x and Java 18. Thank you very much!

**Comment by larsgrefer** [comment]
With the Update from Gradle 7 to 8, we skipped over 7 directly to 8 as well. From then on the major and minor versions are in sync with Gradle.

I've updated the README and our documentation to reflect this.
