### ISSUE TITLE
Upgrade AspectJ to 1.9.21 (Java 21 support)

### ISSUE THREAD

**Issue by vladimirfx** [freefair/gradle-plugins#988]
Official Java 21 support for AspectJ has been released (https://github.com/eclipse-aspectj/aspectj/issues/260). Please release  FreeFair plugins with this AspectJ 1.9.21 as default.

Current workaround:

```kotlin
configurations {
    all {
        resolutionStrategy.dependencySubstitution.all {
            val moduleSelector = requested as? ModuleComponentSelector
            if (moduleSelector?.group == "org.aspectj") {
                useTarget(
                    "${moduleSelector.group}:${moduleSelector.module}:1.9.21",
                    "Use Java 21 compatible version"
                )
            }
        }
    }
}

```

Thank you for the best AspectJ plugin!

**Comment by larsgrefer** [comment]
The gradle plugin has no default version. It infers the AJC version from the AspectJ jars (aspectjrt.jar, aspectjtools.jar) already present on the runtime classpath or aspect path.

So upgrading your aspects or your classpath to aspectjrt 1.9.21 should be sufficient.

**Comment by vladimirfx** [comment]
Yes, after upgrading to Spring Boot 3.2.1 which uses AspectJ 1.9.21, no workaround is needed.

As I say - your plugin is simply the best on the market! 

Thank you
